import { useState, useEffect, useRef, useCallback } from "react";
import type { PluginListenerHandle } from "@capacitor/core";
import { CSS } from "./eveStyles";
import {
  streamChat,
  fetchState,
  resolveConfirm,
  actOnAttention,
  transcribeAudio,
  speakText,
  fetchWardrobe,
  postWear,
  wardrobeImgUrl,
  forwardSms,
  forwardNotification,
  reportSmsSent,
  runJob,
  type EveState,
  type PendingConfirm,
} from "./eveApi";
import { initPush } from "./push";
import {
  smsSupported,
  checkReadSmsPermissions,
  requestReadSmsPermissions,
  onSmsReceived,
  sendSms,
  checkSendSmsPermissions,
  requestSendSmsPermissions,
} from "./native/sms";
import {
  isNotificationAccessEnabled,
  openNotificationAccessSettings,
  onNotificationPosted,
} from "./native/notifications";

/* ============================================================
   EVE — Executive Voice Engine · App shell
   Churlish Media · Presentation ported from the approved v4
   editorial design. Every user-visible EVE line is generated by
   the brain (01 §6 rule 1) — there are no scripted replies here.
   ============================================================ */

type EveMode = "idle" | "listening" | "thinking" | "speaking" | "alert";
type Tab = "today" | "eve" | "ops" | "wire";
type Look = { id: string; name: string; img?: string; status: string };
type Msg = { id: string; role: "eve" | "user"; text: string };

// Quick prompts seed a REAL message to the brain — never a canned reply.
const CHIPS = ["plan my week", "draft me an email", "what's slipping?", "stress-test a decision"];

const STATE_LABEL: Record<EveMode, string> = {
  idle: "HERE — LISTENING FOR YOU",
  listening: "LISTENING",
  thinking: "THINKING",
  speaking: "SPEAKING",
  alert: "TRIPWIRE — ATTENTION",
};
const FOLIO: Record<Tab, string> = {
  today: "N°01 / 04",
  eve: "N°02 / 04",
  ops: "N°03 / 04",
  wire: "N°04 / 04",
};
const STATUS_LINE: Record<Tab, string> = {
  today: "watching the floor",
  eve: "right here",
  ops: "running the fleet",
  wire: "wires checked, honestly",
};
// The wire reads in her language, not the connector registry's.
const WIRE_NAME: Record<string, string> = {
  deepgram: "Deepgram — her ears",
  elevenlabs: "ElevenLabs Voice",
};
const HORIZON = ["Meta Ads — later", "Even G2 Glasses — ph.5"];

const CORE_BG = "radial-gradient(circle at 50% 38%, rgba(240,237,232,.85), #1CB9C8 40%, #063A42 80%)";
const ALERT_BG = "radial-gradient(circle at 50% 38%, rgba(240,237,232,.9), #C41E3A 42%, #4A0E1A 78%)";
const CORE_SHADOW = "0 0 46px rgba(28,185,200,.5), 0 0 110px rgba(0,122,135,.3), inset 0 -8px 22px rgba(0,0,0,.4)";
const ALERT_SHADOW = "0 0 46px rgba(196,30,58,.55), 0 0 110px rgba(196,30,58,.28), inset 0 -8px 22px rgba(0,0,0,.4)";

const CONV_KEY = "eve.conversationId";
const WEAR_KEY = "eve.wearing";

/* ---- the entity: rings, core, ripples, thinking arc, speaking bars ----
   Sizes follow the design: compact when her portrait carries the plate,
   full-size when the core IS the portrait. */
function EveEntity({ mode, compact }: { mode: EveMode; compact: boolean }) {
  const alert = mode === "alert";
  const zone = compact ? 86 : 200;
  const core = compact ? 48 : 116;
  const rOut = compact ? 74 : 176;
  const rIn = compact ? 60 : 144;
  return (
    <div
      className={`corezone${alert ? " alert" : ""}`}
      style={{ height: zone }}
      role="img"
      aria-label={`EVE — ${mode}`}
    >
      <div className="ring-out" style={{ width: rOut, height: rOut }} />
      <div className="ring-in" style={{ width: rIn, height: rIn }} />
      {mode === "thinking" && <div className="ring-think" style={{ width: rIn, height: rIn }} />}
      {mode === "listening" && (
        <>
          <div className="rip" style={{ width: rOut, height: rOut }} />
          <div className="rip rip2" style={{ width: rOut, height: rOut }} />
        </>
      )}
      <div
        className="core"
        style={{
          width: core,
          height: core,
          background: alert ? ALERT_BG : CORE_BG,
          boxShadow: alert ? ALERT_SHADOW : CORE_SHADOW,
        }}
      >
        {mode === "speaking" &&
          [0, 0.15, 0.3, 0.45, 0.6].map((d) => (
            <span key={d} className="wave" style={{ animationDelay: `${d}s` }} />
          ))}
      </div>
    </div>
  );
}

const IconCheck = () => (
  <svg width="14" height="14" viewBox="0 0 16 16" fill="none" stroke="#1CB9C8" strokeWidth="2" strokeLinecap="round">
    <path d="M3 8.5l3.5 3.5L13 4.5" />
  </svg>
);
const IconPause = () => (
  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="rgba(240,237,232,.6)" strokeWidth="2" strokeLinecap="round">
    <path d="M5 3v8M9 3v8" />
  </svg>
);
const IconX = () => (
  <svg width="12" height="12" viewBox="0 0 14 14" fill="none" stroke="rgba(240,237,232,.6)" strokeWidth="2" strokeLinecap="round">
    <path d="M3 3l8 8M11 3l-8 8" />
  </svg>
);

export default function EveApp() {
  const [booted, setBooted] = useState(false);
  const [bootLeaving, setBootLeaving] = useState(false);
  const [tab, setTab] = useState<Tab>("today");
  const [mode, setMode] = useState<EveMode>("idle");
  const [messages, setMessages] = useState<Msg[]>([]);
  const [errNote, setErrNote] = useState<string | null>(null);
  const [toolNote, setToolNote] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [micNote, setMicNote] = useState(false);
  const [wardrobe, setWardrobe] = useState(false);
  const [looks, setLooks] = useState<Look[]>([]);
  const [now, setNow] = useState(() => new Date());
  const [live, setLive] = useState<EveState>({ online: false });
  // RED-tier confirm cards (02 §6) + their resolution notes.
  const [confirms, setConfirms] = useState<PendingConfirm[]>([]);
  const [confirmNote, setConfirmNote] = useState<Record<string, string>>({});
  const [recording, setRecording] = useState(false);
  const [opsBusy, setOpsBusy] = useState<string | null>(null);
  const [jobBusy, setJobBusy] = useState(false);
  const [jobNote, setJobNote] = useState<string | null>(null);
  // Her senses (Phase 4, 05 §7): live enabled state for the Wire row.
  const [smsSense, setSmsSense] = useState(false);
  const [notifSense, setNotifSense] = useState(false);

  const convId = useRef<string | null>(localStorage.getItem(CONV_KEY));
  const busy = useRef(false);
  const abortRef = useRef<AbortController | null>(null);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const lastInputWasVoice = useRef(false);
  const ttsAvailable = useRef(false);
  const senseHandles = useRef<PluginListenerHandle[]>([]);
  const smsWired = useRef(false);
  const notifWired = useRef(false);
  const msgSeq = useRef(0);
  const scrollRef = useRef<HTMLDivElement | null>(null);

  const later = (fn: () => void, ms: number) => {
    const id = setTimeout(fn, ms);
    timers.current.push(id);
  };
  const newId = () => `m${++msgSeq.current}`;

  // ---- her senses (Phase 4, 05 §7): forward texts + notifications to the
  // brain's transient buffers while the app is open. Wiring is idempotent,
  // and nothing here ever PROMPTS — the permission asks live behind the
  // "ENABLE HER SENSES" buttons on the Wire screen (lazy, 05 §7).
  const wireSmsListener = useCallback(async () => {
    if (!smsWired.current) {
      smsWired.current = true;
      senseHandles.current.push(await onSmsReceived((e) => void forwardSms(e)));
    }
    setSmsSense(true);
  }, []);

  const wireNotificationListener = useCallback(async () => {
    if (!notifWired.current) {
      notifWired.current = true;
      senseHandles.current.push(
        await onNotificationPosted((e) => {
          if (e.package === "com.churlish.eve") return; // her own pings — no feedback loop
          void forwardNotification(e);
        }),
      );
    }
    setNotifSense(true);
  }, []);

  const refreshSenses = useCallback(async () => {
    if (!smsSupported()) return;
    // Wire only what's ALREADY granted — never auto-request on boot.
    const { sms } = await checkReadSmsPermissions();
    if (sms === "granted") void wireSmsListener();
    if (await isNotificationAccessEnabled()) void wireNotificationListener();
    else setNotifSense(false); // revoked in settings — show it honestly
  }, [wireSmsListener, wireNotificationListener]);

  useEffect(() => {
    const clock = setInterval(() => setNow(new Date()), 30_000);
    const t = timers.current;
    // FCM registration + deeplink routing (native only; no-op in the browser).
    initPush((deeplink) => {
      if (deeplink === "eve://today") setTab("today");
      else if (deeplink === "eve://ops") setTab("ops");
    });
    // Senses: wire whatever's already granted; re-check with the state poll
    // so flipping notification access in settings lands within a minute.
    void refreshSenses();
    // Her real wardrobe — Brandon's own renders, served by the brain (05 §5).
    // These are HIS uploads: pre-approved by definition; his last worn pick
    // persists locally. Keeps RETRYING with the state poll until the brain
    // answers, so one blip at launch doesn't strip her closet for the session.
    let wardrobeLoaded = false;
    const loadWardrobe = () =>
      fetchWardrobe().then(({ wearing, looks: ws }) => {
        if (!ws.length) return;
        // The brain is the single truth for "wearing" — she changes her own
        // look with wear_look, and King's taps post there too. localStorage
        // is only the pre-brain fallback.
        const worn = wearing ?? localStorage.getItem(WEAR_KEY);
        if (wardrobeLoaded) {
          // Later polls: only sync the worn look (hers may have changed).
          if (worn) {
            setLooks((ls) =>
              ls.some((l) => l.id === worn && l.status !== "wearing")
                ? ls.map((l) => ({
                    ...l,
                    status: l.id === worn ? "wearing" : l.status === "wearing" ? "approved" : l.status,
                  }))
                : ls,
            );
          }
          return;
        }
        wardrobeLoaded = true;
        setLooks(
          ws.map((w) => ({
            id: w.file,
            name: w.name,
            img: wardrobeImgUrl(w),
            status: (worn ? w.file === worn : w.file.toLowerCase() === "base.png") ? "wearing" : "approved",
          })),
        );
      });
    // Live ledger for Today/Ops — refresh every 60s (wardrobe piggybacks
    // until it lands once).
    const loadState = () =>
      fetchState().then((s) => {
        setLive(s);
        ttsAvailable.current = !!s.connectors?.find((c) => c.key === "elevenlabs")?.connected;
        void loadWardrobe(); // cheap JSON; keeps her self-chosen look in sync
        void refreshSenses(); // cheap native checks; never prompts
      });
    loadState();
    loadWardrobe();
    const stateTimer = setInterval(loadState, 60_000);
    return () => {
      clearInterval(clock);
      clearInterval(stateTimer);
      t.forEach(clearTimeout);
      abortRef.current?.abort();
      senseHandles.current.forEach((h) => void h.remove());
    };
  }, []);

  // Keep the newest line in view as she streams.
  useEffect(() => {
    if (tab !== "eve") return;
    const el = scrollRef.current;
    if (el) el.scrollTop = el.scrollHeight;
  }, [messages, tab, confirms.length]);

  // ---- the live brain call ----
  const runMessage = useCallback(async (text: string, showUser = true, viaVoice = false) => {
    if (busy.current || !text.trim()) return;
    busy.current = true;
    lastInputWasVoice.current = viaVoice;
    abortRef.current = new AbortController();
    setErrNote(null);
    setToolNote(null);
    const eveId = newId();
    // Optimistic user line, then an empty EVE line that fills token by token.
    setMessages((ms) => [
      ...ms,
      ...(showUser ? [{ id: newId(), role: "user" as const, text }] : []),
      { id: eveId, role: "eve" as const, text: "" },
    ]);
    setMode("thinking");

    await streamChat(text, convId.current, "app", {
      onState: (s) => {
        if (s === "speaking") setMode("speaking");
        else if (s === "idle") setMode("idle");
      },
      onToken: (tk) =>
        setMessages((ms) => ms.map((m) => (m.id === eveId ? { ...m, text: m.text + tk } : m))),
      onTool: (name) => setToolNote(name),
      onConfirm: (c) => setConfirms((cs) => (cs.some((x) => x.id === c.id) ? cs : [...cs, c])),
      onDone: ({ conversationId, fullText }) => {
        convId.current = conversationId;
        localStorage.setItem(CONV_KEY, conversationId);
        setMode("idle");
        setToolNote(null);
        busy.current = false;
        // Voice loop (05 §3): spoken question → spoken answer. Degrades to
        // text silently when ElevenLabs isn't wired.
        if (lastInputWasVoice.current && ttsAvailable.current && fullText.trim()) {
          void speakText(fullText).then((url) => {
            if (!url) return;
            const audio = new Audio(url);
            setMode("speaking");
            audio.onended = () => {
              setMode("idle");
              URL.revokeObjectURL(url);
            };
            audio.play().catch(() => setMode("idle"));
          });
        }
      },
      onError: (m) => {
        setErrNote(m);
        setMode("idle");
        setToolNote(null);
        busy.current = false;
        // Drop the empty shell so a failure never reads as her saying nothing.
        setMessages((ms) => ms.filter((x) => !(x.id === eveId && !x.text)));
      },
    }, abortRef.current.signal);
  }, []);

  const sendText = () => {
    const t = draft.trim();
    if (!t) return;
    setDraft("");
    runMessage(t);
  };

  // ---- RED-tier confirm resolution ----
  const decideConfirm = async (c: PendingConfirm, approve: boolean) => {
    setConfirmNote((n) => ({ ...n, [c.id]: "…" }));
    const r = await resolveConfirm(c.id, c.hash, approve);
    let note: string;
    if (r.ok && r.clientAction?.type === "send_sms") {
      // SMS leaves from HIS SIM (02 §6 / 05 §7): the brain approved the exact
      // payload; this phone transmits it. Only reachable through an explicit
      // approve — the ONLY path that ever calls sendSms.
      const p = r.clientAction.payload as { phoneNumber: string; message: string };
      try {
        let { sms } = await checkSendSmsPermissions();
        if (sms !== "granted") ({ sms } = await requestSendSmsPermissions());
        if (sms !== "granted") throw new Error("SEND_SMS permission denied");
        await sendSms({ phoneNumber: p.phoneNumber, message: p.message });
        void reportSmsSent(p.phoneNumber, p.message);
        note = "SENT from your phone";
      } catch (err) {
        note = `FAILED — ${err instanceof Error ? err.message : "send error"}`;
      }
    } else {
      note = r.ok ? (r.executed ? `SENT — ${r.detail ?? ""}` : "CANCELLED") : `FAILED — ${r.error ?? "unknown"}`;
    }
    setConfirmNote((n) => ({ ...n, [c.id]: note }));
    later(() => {
      setConfirms((cs) => cs.filter((x) => x.id !== c.id));
      setConfirmNote((n) => {
        const { [c.id]: _gone, ...rest } = n;
        return rest;
      });
    }, 5000);
    fetchState().then(setLive);
  };

  // ---- her senses: the lazy permission asks (Wire screen buttons) ----
  const enableSmsSense = async () => {
    const { sms } = await requestReadSmsPermissions();
    if (sms === "granted") void wireSmsListener();
  };
  const enableNotifSense = async () => {
    // Notification access is a settings toggle, not a runtime prompt: send
    // him there; the state poll wires the listener once he flips it on.
    if (await isNotificationAccessEnabled()) return void wireNotificationListener();
    await openNotificationAccessSettings();
  };

  // ---- Ops actions (approve / hold / dismiss) ----
  const opsAction = async (id: string, action: "approve" | "hold" | "dismiss") => {
    setOpsBusy(id);
    await actOnAttention(id, action);
    setOpsBusy(null);
    fetchState().then(setLive);
  };

  // ---- § RUN HER DAY: fires her REAL morning brief, not a scripted preview ----
  const runHerDay = async () => {
    if (jobBusy) return;
    setJobBusy(true);
    setJobNote(null);
    const r = await runJob("morning_brief", true);
    setJobNote(
      r.ok
        ? "BRIEF GENERATED — IT'S THE LINE AT THE TOP OF THIS SCREEN"
        : `NO BRIEF — ${(r.reason ?? r.error ?? "the brain declined").toUpperCase()}`,
    );
    setJobBusy(false);
    fetchState().then(setLive);
    later(() => setJobNote(null), 9000);
  };

  const wake = () => {
    setBootLeaving(true);
    later(() => {
      setBooted(true);
      setTab("eve");
      // Generated greeting — not a canned string. Seed is a system event, not shown.
      runMessage("[King just opened the app. Greet him and give a short read on the moment.]", false);
    }, 480);
  };

  // Voice in (05 §3): tap to record, tap to stop → Deepgram via the brain →
  // the transcript goes through the normal chat loop.
  const micTap = async () => {
    if (recording) {
      recorderRef.current?.stop();
      return;
    }
    const sttReady = live.connectors?.find((c) => c.key === "deepgram")?.connected;
    if (!sttReady) {
      setMicNote(true);
      later(() => setMicNote(false), 2600);
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mime = MediaRecorder.isTypeSupported("audio/webm;codecs=opus")
        ? "audio/webm;codecs=opus"
        : MediaRecorder.isTypeSupported("audio/mp4")
          ? "audio/mp4"
          : "";
      const rec = new MediaRecorder(stream, mime ? { mimeType: mime } : undefined);
      const chunks: Blob[] = [];
      rec.ondataavailable = (e) => {
        if (e.data.size > 0) chunks.push(e.data);
      };
      rec.onstop = async () => {
        stream.getTracks().forEach((tr) => tr.stop());
        setRecording(false);
        setMode("thinking");
        const blob = new Blob(chunks, { type: mime || "audio/webm" });
        const r = await transcribeAudio(blob);
        if (r.ok && r.transcript?.trim()) {
          runMessage(r.transcript, true, true);
        } else {
          setMode("idle");
          setErrNote(r.error || "didn't catch that — try again");
        }
      };
      recorderRef.current = rec;
      rec.start();
      setRecording(true);
      setMode("listening");
    } catch {
      setErrNote("microphone unavailable — check the permission");
    }
  };

  const wearing = looks.find((l) => l.status === "wearing") ?? null;
  const wear = (id: string) => {
    localStorage.setItem(WEAR_KEY, id);
    void postWear(id);
    setLooks((ls) =>
      ls.map((l) => ({
        ...l,
        status: l.id === id ? "wearing" : l.status === "wearing" ? "approved" : l.status,
      })),
    );
  };

  // ---- live clock / date eyebrow ----
  const clockStr = now.toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" });
  const dow = now.toLocaleDateString("en-US", { weekday: "short" }).toUpperCase();
  const md = now.toLocaleDateString("en-US", { month: "short", day: "numeric" }).toUpperCase();
  const weekNo = Math.ceil(
    ((now.getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / 86400000 +
      new Date(now.getFullYear(), 0, 1).getDay() +
      1) /
      7,
  );
  const greeting = now.getHours() < 12 ? "Morning" : now.getHours() < 18 ? "Afternoon" : "Evening";
  const statusLine = live.online ? STATUS_LINE[tab] : "brain unreachable";

  // ---- ops slicing + folio numbering (sections are data-driven) ----
  const pendings = live.online ? live.pendingConfirms ?? [] : [];
  const attention = live.online ? live.attentionItems ?? [] : [];
  const tripwires = attention.filter((a) => a.kind === "tripwire");
  const inbox = attention.filter((a) => a.kind !== "tripwire");
  const quietCount = (live.clients ?? []).filter(
    (c) => c.days_quiet !== null && c.days_quiet > c.cadence_days,
  ).length;
  let opsN = 0;
  const fConfirm = pendings.length ? String(++opsN).padStart(2, "0") : "";
  const fJobs = String(++opsN).padStart(2, "0");
  const fInbox = String(++opsN).padStart(2, "0");
  const fPulse = String(++opsN).padStart(2, "0");
  const fTrip = tripwires.length ? String(++opsN).padStart(2, "0") : "";

  // ---- wire grouping: honest status, only what's wired reads LIVE ----
  const wireItems = [
    { name: "EVE Brain", connected: live.online },
    { name: "Supabase — her memory", connected: live.online },
    ...(live.connectors ?? []).map((c) => ({
      name: WIRE_NAME[c.key] ?? c.name,
      connected: c.connected,
    })),
  ];
  const liveWire = wireItems.filter((i) => i.connected);
  const coldWire = wireItems.filter((i) => !i.connected);
  const sttOn = !!live.connectors?.find((c) => c.key === "deepgram")?.connected;
  const ttsOn = !!live.connectors?.find((c) => c.key === "elevenlabs")?.connected;

  const wireGroups: { label: string; color: string; items: string[] }[] = [
    ...(liveWire.length ? [{ label: "LIVE", color: "#1CB9C8", items: liveWire.map((i) => i.name) }] : []),
    ...(coldWire.length
      ? [
          {
            label: live.online ? "KEY NEEDED" : "UNREACHABLE",
            color: "rgba(240,237,232,.7)",
            items: coldWire.map((i) => i.name),
          },
        ]
      : []),
    { label: "ON THE HORIZON", color: "rgba(240,237,232,.4)", items: HORIZON },
  ];

  return (
    <div className="eve-root">
      <style>{CSS}</style>
      <div className="eve-frame">
        <div className="eve-glow" />

        {/* ---------- header ---------- */}
        <div className="eve-head">
          <span className="eve-dot" />
          <span className="eve-wm disp">EVE</span>
          <span className="eve-sub mono">
            EXECUTIVE
            <br />
            VOICE ENGINE
          </span>
          <span className="eve-rule" />
          <span className="eve-folio mono">{FOLIO[tab]}</span>
        </div>

        {/* ---------- TODAY ---------- */}
        {tab === "today" && (
          <div className="eve-screen">
            <div className="eyebrow mono">
              {dow} · {md} · {clockStr} · WK {weekNo} · OMAHA · {statusLine.toUpperCase()}
            </div>
            <h1 className="h1 disp">
              {greeting},
              <br />
              Brandon.
            </h1>
            <p className="lede">
              {live.online && live.latestBrief?.text
                ? live.latestBrief.text
                : live.online
                  ? "No brief on the board yet. Run her day below, or just tell her what matters — she'll set the three."
                  : "Her brain is unreachable, so this screen is a shell. Everything below fills in the moment she answers."}
            </p>

            {/* 01 — the floor */}
            <section className="sec first">
              <span className="ghost disp">01</span>
              <div className="seclab mono">§ THE FLOOR — SALES CONVERSATIONS</div>
              <div className="floorrow">
                <span className="floornum disp">
                  {live.floor?.count ?? 0}
                  <em>/{live.floor?.goal ?? 3}</em>
                </span>
                <span className="floorcap">
                  conversations
                  <br />
                  booked this week
                </span>
              </div>
              <div className="bars">
                {Array.from({ length: live.floor?.goal ?? 3 }).map((_, i) => (
                  <span key={i} className={(live.floor?.count ?? 0) > i ? "on" : ""} />
                ))}
              </div>
              <div className="floorfoot">
                {live.online
                  ? "Real conversations logged this week — calls and meetings, not drafts."
                  : "Offline — the count lands when her brain answers."}
              </div>
            </section>

            {/* 02 — today's three */}
            <section className="sec">
              <span className="ghost disp">02</span>
              <div className="seclab mono">§ TODAY'S THREE</div>
              <div className="three">
                {live.todaysThree?.length ? (
                  live.todaysThree.map((t) => {
                    const due = !!t.due_at && new Date(t.due_at).getTime() < now.getTime();
                    return (
                      <div className="item" key={t.id}>
                        <span className={`n mono${due ? " due" : ""}`}>
                          {String(t.priority).padStart(2, "0")}
                        </span>
                        <div>
                          <div className="t">{t.title}</div>
                          {t.detail && <div className="m">{t.detail}</div>}
                        </div>
                      </div>
                    );
                  })
                ) : (
                  <div className="item">
                    <span className="n mono">—</span>
                    <div>
                      <div className="t">{live.online ? "Nothing set yet" : "Waiting on her brain"}</div>
                      <div className="m">
                        {live.online
                          ? "tell her what matters today, or capture it — she'll slot it"
                          : "the three arrive with the next successful poll"}
                      </div>
                    </div>
                  </div>
                )}
              </div>
            </section>

            {/* 03 — run her day (a REAL job, not a preview) */}
            <section className="sec">
              <span className="ghost disp">03</span>
              <div className="seclab mono">§ RUN HER DAY</div>
              <div className="playrow">
                <button
                  className="play"
                  onClick={runHerDay}
                  disabled={jobBusy || !live.online}
                  aria-label="Run her morning brief now"
                >
                  <span className="playtri" />
                </button>
                <div className="playtxt">
                  Morning brief → midday nudge → tripwire → close-out. She runs the cadence on
                  her own clock.
                  <br />
                  <span style={{ fontStyle: "italic", color: "rgba(28,185,200,.75)" }}>
                    {jobBusy
                      ? "she's writing it now…"
                      : jobNote
                        ? jobNote.toLowerCase()
                        : live.online
                          ? "this fires the real brief now"
                          : "needs her brain — currently unreachable"}
                  </span>
                </div>
              </div>
            </section>

            {/* 04 — capture */}
            <section className="sec">
              <span className="ghost disp">04</span>
              <div className="seclab mono">§ CAPTURE — ANY DOOR IN</div>
              <p className="secnote" style={{ fontSize: 15 }}>
                Speak it, type it, forward it. I date it, file it to the right client, keep the
                source thread. <b>The inbox exists to be emptied.</b>
              </p>
            </section>

            {/* 05 — live minis */}
            <section className="sec last">
              <div className="twoup">
                <div className="col">
                  <div className="k mono">ROUTINES</div>
                  <div className="v">
                    {live.routines?.length
                      ? live.routines.slice(0, 3).map((r) => (
                          <div key={r.id}>
                            {r.name} — {r.streak}d streak
                          </div>
                        ))
                      : live.online
                        ? "none tracked yet"
                        : "—"}
                  </div>
                </div>
                <div className="div" />
                <div className="col">
                  <div className="k mono">CLIENT PULSE</div>
                  <div className="v">
                    {live.online ? (
                      <>
                        {live.clients?.length ?? 0} on the roster
                        <br />
                        {quietCount} past cadence
                      </>
                    ) : (
                      "—"
                    )}
                  </div>
                </div>
              </div>
            </section>
          </div>
        )}

        {/* ---------- EVE / TALK ---------- */}
        {tab === "eve" && (
          <div className="eve-screen" ref={scrollRef}>
            <div className="eyebrow mono">§ FIG.01 — EVE CORE · LIVE PLATE</div>

            <div className="plate">
              <div className="br tl" />
              <div className="br tr" />
              <div className="br bl" />
              <div className="br brr" />

              {/* Her worn look carries the plate; the core is the fallback
                  and the speaking indicator (05 §5). */}
              {wearing?.img && (
                <div className={`portrait${mode === "alert" ? " alert" : ""}`}>
                  <img src={wearing.img} alt={`EVE — ${wearing.name}`} />
                </div>
              )}

              <EveEntity mode={mode} compact={!!wearing?.img} />

              <div className="staterow">
                <span className={`statelab mono${mode === "alert" ? " alert" : ""}`}>
                  STATE · {STATE_LABEL[mode]}
                </span>
                <span className="statetag mono">
                  {toolNote
                    ? `· ${toolNote.replace(/_/g, " ").toUpperCase()}`
                    : live.online
                      ? "BRAIN LIVE"
                      : "BRAIN UNREACHABLE"}
                </span>
              </div>
            </div>

            {/* messages — typographic, never bubbles */}
            <div className="msgs">
              {messages.length === 0 && (
                <div>
                  <div className="evelab mono">EVE —</div>
                  <div className="evetext" style={{ color: "rgba(240,237,232,.45)" }}>
                    Type below or pick a prompt. Every line she says is written live — real
                    replies, real memory across this conversation.
                  </div>
                </div>
              )}
              {messages.map((m) =>
                m.role === "eve" ? (
                  <div key={m.id}>
                    <div className="evelab mono">EVE —</div>
                    <div className="evetext">
                      {m.text || (mode === "thinking" ? "…" : "")}
                    </div>
                  </div>
                ) : (
                  <div key={m.id}>
                    <div className="youwrap">
                      <div className="youlab mono">YOU —</div>
                      <div className="youtext">{m.text}</div>
                    </div>
                  </div>
                ),
              )}
              {errNote && <div className="errline mono">CONNECTION: {errNote}</div>}

              {/* RED-tier confirm cards (02 §6): exact payload + approve round-trip */}
              {confirms.map((c) => (
                <div className="confirm" key={c.id}>
                  <div className="hd mono">
                    RED TIER · {c.kind.replace(/_/g, " ").toUpperCase()} · NOTHING SENDS WITHOUT YOU
                  </div>
                  <div className="sum">{c.summary}</div>
                  {Object.entries(c.payload).map(([k, v]) => (
                    <div className="field" key={k}>
                      <b>{k.toUpperCase()}</b>
                      {String(v).slice(0, 240)}
                    </div>
                  ))}
                  {confirmNote[c.id] ? (
                    <div className={`cnote mono${confirmNote[c.id].startsWith("SENT") ? " ok" : ""}`}>
                      {confirmNote[c.id]}
                    </div>
                  ) : (
                    <div className="chips" style={{ columnGap: 18, margin: "6px 0 0" }}>
                      <button className="chip" style={{ color: "#1CB9C8" }} onClick={() => decideConfirm(c, true)}>
                        approve — send it →
                      </button>
                      <button
                        className="chip"
                        style={{ color: "rgba(240,237,232,.5)" }}
                        onClick={() => decideConfirm(c, false)}
                      >
                        cancel →
                      </button>
                    </div>
                  )}
                </div>
              ))}
            </div>

            <div className="chips">
              {CHIPS.map((c) => (
                <button key={c} className="chip" disabled={mode !== "idle"} onClick={() => runMessage(c)}>
                  {c} →
                </button>
              ))}
            </div>

            <div className="inrow">
              <button
                className={`mic${recording ? " rec" : mode === "listening" ? " on" : ""}`}
                onClick={micTap}
                aria-label={recording ? "Stop and send" : "Talk to EVE"}
              >
                <svg width="22" height="22" viewBox="0 0 20 20" fill="none" stroke="#F0EDE8" strokeWidth="1.5">
                  <rect x="7" y="2" width="6" height="11" rx="3" />
                  <path d="M4 9.5a6 6 0 0 0 12 0M10 15.5V19" />
                </svg>
              </button>
              <input
                className="tin"
                value={draft}
                onChange={(e) => setDraft(e.target.value)}
                onKeyDown={(e) => {
                  if (e.key === "Enter") sendText();
                }}
                placeholder="Type to her — she remembers"
                aria-label="Message EVE"
              />
              <button className="sendb" onClick={sendText} aria-label="Send">
                <svg width="20" height="20" viewBox="0 0 18 18" fill="none" stroke="#1CB9C8" strokeWidth="1.6" strokeLinejoin="round">
                  <path d="M16 2L2 8l5.5 2.5L10 16l6-14z" />
                </svg>
              </button>
            </div>

            <div className="footrow">
              <span className="foottag mono">
                {recording ? (
                  <b style={{ color: "#C41E3A" }}>LISTENING — TAP AGAIN TO SEND</b>
                ) : micNote ? (
                  <b style={{ color: "#1CB9C8" }}>HER EARS NEED THE DEEPGRAM KEY</b>
                ) : (
                  <>
                    VOICE ·{" "}
                    <b>
                      {sttOn ? "ears live" : "ears await key"} · {ttsOn ? "voice live" : "voice awaits key"}
                    </b>
                  </>
                )}
              </span>
              <button className="wardrobe-open mono" onClick={() => setWardrobe(true)}>
                LOOK · {wearing?.name ?? "CORE"} — WARDROBE →
              </button>
            </div>
          </div>
        )}

        {/* ---------- OPS ---------- */}
        {tab === "ops" && (
          <div className="eve-screen">
            <div className="eyebrow mono">OPERATIONS · THE FLEET REPORTS</div>
            <h1 className="h1 sm disp">
              Your signature,
              <br />
              not your time.
            </h1>
            <p className="lede ops">
              Everything below arrives finished. Approve, hold, or send — I handle the rest.
            </p>

            {/* RED tier — waiting on your thumb (02 §6) */}
            {!!pendings.length && (
              <section className="sec red first">
                <span className="ghost red disp">{fConfirm}</span>
                <div className="seclab mono red">§ WAITING ON YOUR THUMB — RED TIER</div>
                <div className="secbody">
                  {pendings.map((c) => (
                    <div className="oprow" key={c.id}>
                      <div className="t">
                        {c.summary}
                        <small>
                          expires{" "}
                          {new Date(c.expiresAt).toLocaleTimeString("en-US", {
                            hour: "numeric",
                            minute: "2-digit",
                          })}
                        </small>
                      </div>
                      {confirmNote[c.id] ? (
                        <span className="donelab mono">{confirmNote[c.id]}</span>
                      ) : (
                        <>
                          <button className="okb hit44" aria-label="Approve send" onClick={() => decideConfirm(c, true)}>
                            <IconCheck />
                          </button>
                          <button className="ghb hit44" aria-label="Cancel send" onClick={() => decideConfirm(c, false)}>
                            <IconX />
                          </button>
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </section>
            )}

            {/* jobs in flight */}
            <section className={`sec${pendings.length ? "" : " first"}`}>
              <span className="ghost disp">{fJobs}</span>
              <div className="seclab mono">§ JOBS IN FLIGHT</div>
              <div className="jobs">
                {live.jobs?.length ? (
                  live.jobs.map((j) => (
                    <div className="jobrow" key={j.id}>
                      <div>
                        <span className="a">{j.agent || "eve"}</span>
                        <span className="b"> — {j.title}</span>
                      </div>
                      <span
                        className="s mono"
                        style={{
                          color:
                            j.status === "running"
                              ? "#1CB9C8"
                              : j.status === "in_approvals"
                                ? "rgba(240,237,232,.6)"
                                : "rgba(240,237,232,.38)",
                        }}
                      >
                        {j.status.replace(/_/g, " ").toUpperCase()}
                      </span>
                    </div>
                  ))
                ) : (
                  <div className="secnote">
                    {live.online
                      ? "Nothing in flight. Give her the job — by agent name or just the outcome."
                      : "Offline — the fleet reports in when her brain answers."}
                  </div>
                )}
              </div>
              {!!live.jobs?.length && (
                <div className="aside">one approval batch, not a stream of questions</div>
              )}
            </section>

            {/* approval inbox — live attention items */}
            <section className="sec tight">
              <span className="ghost disp">{fInbox}</span>
              <div style={{ display: "flex", justifyContent: "space-between", marginBottom: 10 }}>
                <span className="seclab mono" style={{ marginBottom: 0 }}>
                  § APPROVAL INBOX
                </span>
                <span className="mono" style={{ fontSize: 10, letterSpacing: ".1em", color: "rgba(240,237,232,.4)" }}>
                  {inbox.length} queued
                </span>
              </div>
              <div className="secbody">
                {inbox.length ? (
                  inbox.slice(0, 8).map((a) => (
                    <div className="oprow" key={a.id}>
                      <span className="tag mono">
                        {a.kind.replace(/_/g, " ").toUpperCase()} · N{a.nudge_level}
                      </span>
                      <div className="t">
                        {a.message}
                        {a.kind === "silent_client" && a.ref?.draft && (
                          <small>draft ready — approve turns it into a Today task</small>
                        )}
                      </div>
                      {opsBusy === a.id ? (
                        <span className="donelab mono">…</span>
                      ) : (
                        <>
                          <button className="okb hit44" aria-label="Approve" onClick={() => opsAction(a.id, "approve")}>
                            <IconCheck />
                          </button>
                          <button className="ghb hit44" aria-label="Hold 24h" onClick={() => opsAction(a.id, "hold")}>
                            <IconPause />
                          </button>
                          <button className="ghb hit44" aria-label="Dismiss" onClick={() => opsAction(a.id, "dismiss")}>
                            <IconX />
                          </button>
                        </>
                      )}
                    </div>
                  ))
                ) : (
                  <div className="secnote">
                    {live.online
                      ? "Nothing needs you. She'll surface it here when it does."
                      : "Offline — nothing to show until her brain answers."}
                  </div>
                )}
              </div>
            </section>

            {/* client pulse */}
            <section className="sec">
              <span className="ghost disp">{fPulse}</span>
              <div className="seclab mono">
                § CLIENT PULSE{live.online ? ` — ${quietCount} QUIET` : ""}
              </div>
              <div className="pulse">
                {live.clients?.length ? (
                  live.clients.map((cl) => {
                    const hot = cl.days_quiet !== null && cl.days_quiet > cl.cadence_days;
                    return (
                      <div className="pulserow" key={cl.id}>
                        <span className={`d mono${hot ? " hot" : ""}`}>
                          {cl.days_quiet === null ? "NEW" : `${cl.days_quiet}d`}
                        </span>
                        <div>
                          <div className="n">{cl.name}</div>
                          <div className="w">
                            cadence {cl.cadence_days}d
                            {hot ? " — past it. She has an update drafted." : " — inside the window."}
                          </div>
                        </div>
                      </div>
                    );
                  })
                ) : (
                  <div className="secnote">
                    {live.online
                      ? "No clients in the ledger yet — add them and she starts watching cadences."
                      : "Offline — the radar lands when her brain answers."}
                  </div>
                )}
              </div>
            </section>

            {/* tripwires — the only other red on this screen, and only when live */}
            {!!tripwires.length && (
              <section className="sec red">
                <span className="ghost red disp">{fTrip}</span>
                <div className="seclab mono red">§ TRIPWIRE · {tripwires.length} LIVE</div>
                <div className="secbody">
                  {tripwires.map((a) => (
                    <div className="oprow" key={a.id}>
                      <div className="t">{a.message}</div>
                      {opsBusy === a.id ? (
                        <span className="donelab mono">…</span>
                      ) : (
                        <>
                          <button className="okb hit44" aria-label="Approve" onClick={() => opsAction(a.id, "approve")}>
                            <IconCheck />
                          </button>
                          <button className="ghb hit44" aria-label="Hold 24h" onClick={() => opsAction(a.id, "hold")}>
                            <IconPause />
                          </button>
                          <button className="ghb hit44" aria-label="Dismiss" onClick={() => opsAction(a.id, "dismiss")}>
                            <IconX />
                          </button>
                        </>
                      )}
                    </div>
                  ))}
                </div>
              </section>
            )}
          </div>
        )}

        {/* ---------- WIRE ---------- */}
        {tab === "wire" && (
          <div className="eve-screen">
            <div className="eyebrow mono">THE WIRE · SIGNAL REPORT</div>
            <h1 className="h1 sm disp">
              One face.
              <br />
              The whole fleet
              <br />
              behind it.
            </h1>
            <p className="lede ops">
              You talk to me. I route to everything else. Status is honest — only what's wired
              reads LIVE.
            </p>

            {wireGroups.map((g, i) => (
              <section className={`sec tight${i === 0 ? " first" : ""}`} key={g.label}>
                <span className="ghost sm disp">{String(g.items.length).padStart(2, "0")}</span>
                <div className="wgroup">
                  <span className="d" style={{ background: g.color, boxShadow: `0 0 6px ${g.color}` }} />
                  <span className="l mono" style={{ color: g.color }}>
                    § {g.label}
                  </span>
                </div>
                <div className="wchips">
                  {g.items.map((n) => (
                    <span className="wchip" key={n}>
                      <span className="d" style={{ background: g.color, boxShadow: `0 0 5px ${g.color}` }} />
                      {n}
                    </span>
                  ))}
                </div>
              </section>
            ))}

            {/* HER SENSES (Phase 4, 05 §7): lazy permission asks — the system
                prompts fire from THESE taps, never on boot. */}
            <section className="sec tight">
              <span className="ghost sm disp">{String(wireGroups.length + 1).padStart(2, "0")}</span>
              <div className="seclab mono" style={{ fontSize: 10.5, letterSpacing: ".22em", marginBottom: 12 }}>
                § ENABLE HER SENSES
              </div>
              <p className="secnote" style={{ marginBottom: 14 }}>
                Texts and notifications forward to my brain only while the app is open —
                transient, never long-term memory. Replies always go through your thumb.
              </p>
              {smsSupported() ? (
                <div className="senses">
                  <button
                    className={`sense hit44${smsSense ? " on" : ""}`}
                    disabled={smsSense}
                    onClick={enableSmsSense}
                  >
                    {smsSense ? "SMS — LIVE" : "SMS"}
                  </button>
                  <button
                    className={`sense hit44${notifSense ? " on" : ""}`}
                    disabled={notifSense}
                    onClick={enableNotifSense}
                  >
                    {notifSense ? "NOTIFICATIONS — LIVE" : "NOTIFICATIONS"}
                  </button>
                </div>
              ) : (
                <div className="mono" style={{ fontSize: 10, letterSpacing: ".12em", color: "rgba(240,237,232,.35)" }}>
                  ANDROID BUILD ONLY — THE BROWSER HAS NO SMS OR NOTIFICATION ACCESS
                </div>
              )}
            </section>

            <section className="legend">
              <div>
                <span className="k mono" style={{ color: "#1CB9C8" }}>GREEN</span>{" "}
                <span className="v">— I draft and build everything, unprompted.</span>
              </div>
              <div>
                <span className="k mono" style={{ color: "#F0EDE8" }}>YELLOW</span>{" "}
                <span className="v">— built to done, assumptions flagged on top.</span>
              </div>
              <div>
                <span className="k mono" style={{ color: "#C41E3A" }}>RED</span>{" "}
                <span className="v">— nothing external ever sends without you.</span>
              </div>
            </section>
          </div>
        )}

        {/* ---------- wardrobe ---------- */}
        {wardrobe && (
          <>
            <div className="wscrim" onClick={() => setWardrobe(false)} />
            <div className="wsheet">
              <div className="grab" />
              <div className="whead">
                <span className="wlab mono">§ WARDROBE</span>
                <button className="wclose mono" onClick={() => setWardrobe(false)}>
                  CLOSE ✕
                </button>
              </div>
              <h2 className="wh2 disp">How she shows up.</h2>
              <p className="wp">
                Looks change the render, never the mission. Every one of these is a render you
                uploaded — she picks what to wear, and so can you.
              </p>
              {looks.length ? (
                <div className="wgrid">
                  {looks.map((l) => (
                    <button
                      className={`lookc${l.status === "wearing" ? " on" : ""}`}
                      key={l.id}
                      onClick={() => wear(l.id)}
                      aria-label={`Wear ${l.name}`}
                      aria-pressed={l.status === "wearing"}
                    >
                      {l.img && <img src={l.img} alt={l.name} loading="lazy" />}
                      <div className="nm">{l.name}</div>
                    </button>
                  ))}
                </div>
              ) : (
                <p className="wp" style={{ color: "rgba(240,237,232,.4)" }}>
                  Her closet lives on the brain — currently unreachable. It'll be here the moment
                  she answers.
                </p>
              )}
              <div className="wfoot">
                same EVE underneath · {looks.length} looks, hers to choose
              </div>
            </div>
          </>
        )}

        {/* ---------- bottom nav ---------- */}
        <nav className="eve-nav">
          {([
            ["today", "01", "TODAY"],
            ["eve", "02", "EVE"],
            ["ops", "03", "OPS"],
            ["wire", "04", "WIRE"],
          ] as const).map(([id, n, lab]) => (
            <button
              key={id}
              className={`navb${tab === id ? " on" : ""}`}
              onClick={() => setTab(id)}
              aria-label={lab}
              aria-current={tab === id ? "page" : undefined}
            >
              <span className="bar" />
              <span className="n disp">{n}</span>
              <span className="l mono">{lab}</span>
            </button>
          ))}
        </nav>

        {/* ---------- boot ---------- */}
        {!booted && (
          <div className={`boot${bootLeaving ? " boot-out" : ""}`}>
            <EveEntity mode="idle" compact={false} />
            <div className="wm disp">EVE</div>
            <div className="ws mono">EXECUTIVE VOICE ENGINE · CHURLISH MEDIA</div>
            <button className="wakeb" onClick={wake}>
              WAKE HER UP
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
