import { useState, useEffect, useRef, useCallback } from "react";
import type { PluginListenerHandle } from "@capacitor/core";
import { CSS } from "./eveStyles";
import {
  streamChat,
  fetchState,
  resolveConfirm,
  actOnAttention,
  transcribeAudio,
  speakText,
  fetchWardrobe,
  postWear,
  wardrobeImgUrl,
  forwardSms,
  forwardNotification,
  reportSmsSent,
  runJob,
  type EveState,
  type PendingConfirm,
} from "./eveApi";
import { initPush } from "./push";
import {
  smsSupported,
  checkReadSmsPermissions,
  requestReadSmsPermissions,
  onSmsReceived,
  sendSms,
  checkSendSmsPermissions,
  requestSendSmsPermissions,
} from "./native/sms";
import {
  isNotificationAccessEnabled,
  openNotificationAccessSettings,
  onNotificationPosted,
} from "./native/notifications";
import { requestAudioFocus, abandonAudioFocus } from "./native/audioFocus";

/* ============================================================
   EVE — Executive Voice Engine · App shell
   Churlish Media · Presentation ported from the approved v4
   editorial design. Every user-visible EVE line is generated by
   the brain (01 §6 rule 1) — there are no scripted replies here.
   ============================================================ */

type EveMode = "idle" | "listening" | "thinking" | "speaking" | "alert";
type Tab = "today" | "eve" | "ops" | "wire";
type Look = { id: string; name: string; img?: string; status: string };
type Msg = { id: string; role: "eve" | "user"; text: string };

// Quick prompts seed a REAL message to the brain — never a canned reply.
// Every one of these lands on a live capability (fleet, OS, pulse, doctrine).
const CHIPS = ["Run my day", "What's on the board?", "Who's gone quiet?", "What's slipping?"];

// Entity presence meta, straight from his v6 design (dot glyph, label, colors).
const ENT: Record<EveMode, { dot: string; label: string; col: string; aura: string }> = {
  idle: { dot: "○", label: "IDLE — HOLDING THE ROOM", col: "rgba(28,185,200,.8)", aura: "rgba(0,122,135,.3)" },
  listening: { dot: "●", label: "LISTENING — GO AHEAD", col: "#1CB9C8", aura: "rgba(28,185,200,.34)" },
  thinking: { dot: "◐", label: "WORKING THE PROBLEM", col: "#9BEFF7", aura: "rgba(0,122,135,.32)" },
  speaking: { dot: "●", label: "SPEAKING", col: "#1CB9C8", aura: "rgba(28,185,200,.36)" },
  alert: { dot: "▲", label: "ALERT — NEEDS YOUR EYES", col: "#C41E3A", aura: "rgba(196,30,58,.32)" },
};
const ORB_BG = "radial-gradient(circle at 34% 30%, #C9F7FB 0%, #1CB9C8 30%, #007A87 58%, #06272C 100%)";
const ORB_BG_RED = "radial-gradient(circle at 34% 30%, #F7C9D2 0%, #E0526E 30%, #C41E3A 58%, #2C060D 100%)";
const ORB_GLOW = "0 0 36px rgba(28,185,200,.5), 0 0 90px rgba(0,122,135,.35), inset 0 0 20px rgba(201,247,251,.35)";
const ORB_GLOW_RED = "0 0 36px rgba(196,30,58,.5), 0 0 90px rgba(196,30,58,.3), inset 0 0 20px rgba(247,201,210,.35)";
const APP_VERSION = "0.6.6";

const CORE_BG = "radial-gradient(circle at 50% 38%, rgba(240,237,232,.85), #1CB9C8 40%, #063A42 80%)";
const ALERT_BG = "radial-gradient(circle at 50% 38%, rgba(240,237,232,.9), #C41E3A 42%, #4A0E1A 78%)";
const CORE_SHADOW = "0 0 46px rgba(28,185,200,.5), 0 0 110px rgba(0,122,135,.3), inset 0 -8px 22px rgba(0,0,0,.4)";
const ALERT_SHADOW = "0 0 46px rgba(196,30,58,.55), 0 0 110px rgba(196,30,58,.28), inset 0 -8px 22px rgba(0,0,0,.4)";

const CONV_KEY = "eve.conversationId";
const WEAR_KEY = "eve.wearing";

// She writes markdown emphasis by instinct; raw asterisks on screen read as a
// glitch. Render the inline set (bold/italic/code, header lines as bold) and
// nothing heavier — escape first so nothing she says can inject markup.
function mdLite(s: string): string {
  let h = s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  h = h.replace(/`([^`\n]+)`/g, "<code>$1</code>");
  h = h.replace(/\*\*([^*\n]+)\*\*/g, "<b>$1</b>");
  h = h.replace(/\*([^*\s][^*\n]*)\*/g, "<i>$1</i>");
  h = h.replace(/^#{1,4}\s+(.+)$/gm, "<b>$1</b>");
  return h;
}

/* ---- the entity: rings, core, ripples, thinking arc, speaking bars ----
   Lives on the boot screen and as the Talk plate's empty-closet fallback;
   her portrait carries the plate everywhere else. */
function EveEntity({ mode }: { mode: EveMode }) {
  const alert = mode === "alert";
  const zone = 200;
  const core = 116;
  const rOut = 176;
  const rIn = 144;
  return (
    <div
      className={`corezone${alert ? " alert" : ""}`}
      style={{ height: zone }}
      role="img"
      aria-label={`EVE — ${mode}`}
    >
      <div className="ring-out" style={{ width: rOut, height: rOut }} />
      <div className="ring-in" style={{ width: rIn, height: rIn }} />
      {mode === "thinking" && <div className="ring-think" style={{ width: rIn, height: rIn }} />}
      {mode === "listening" && (
        <>
          <div className="rip" style={{ width: rOut, height: rOut }} />
          <div className="rip rip2" style={{ width: rOut, height: rOut }} />
        </>
      )}
      <div
        className="core"
        style={{
          width: core,
          height: core,
          background: alert ? ALERT_BG : CORE_BG,
          boxShadow: alert ? ALERT_SHADOW : CORE_SHADOW,
        }}
      >
        {mode === "speaking" &&
          [0, 0.15, 0.3, 0.45, 0.6].map((d) => (
            <span key={d} className="wave" style={{ animationDelay: `${d}s` }} />
          ))}
      </div>
    </div>
  );
}

export default function EveApp() {
  const [booted, setBooted] = useState(false);
  const [bootLeaving, setBootLeaving] = useState(false);
  const [tab, setTab] = useState<Tab>("today");
  const [mode, setMode] = useState<EveMode>("idle");
  const [messages, setMessages] = useState<Msg[]>([]);
  const [errNote, setErrNote] = useState<string | null>(null);
  const [toolNote, setToolNote] = useState<string | null>(null);
  const [draft, setDraft] = useState("");
  const [micNote, setMicNote] = useState(false);
  const [wardrobe, setWardrobe] = useState(false);
  const [looks, setLooks] = useState<Look[]>([]);
  const [now, setNow] = useState(() => new Date());
  const [live, setLive] = useState<EveState>({ online: false });
  // RED-tier confirm cards (02 §6) + their resolution notes.
  const [confirms, setConfirms] = useState<PendingConfirm[]>([]);
  const [confirmNote, setConfirmNote] = useState<Record<string, string>>({});
  const [recording, setRecording] = useState(false);
  const [opsBusy, setOpsBusy] = useState<string | null>(null);
  const [jobBusy, setJobBusy] = useState(false);
  const [jobNote, setJobNote] = useState<string | null>(null);
  // Her senses (Phase 4, 05 §7): live enabled state for the Wire row.
  const [smsSense, setSmsSense] = useState(false);
  const [notifSense, setNotifSense] = useState(false);
  // CORE vs PORTRAIT presence (his v6 wardrobe toggle). null = auto: portrait
  // the moment a worn look exists, core while the closet is empty.
  const [plateMode, setPlateMode] = useState<"core" | "portrait" | null>(
    () => (localStorage.getItem("eve.plateMode") as "core" | "portrait" | null) ?? null,
  );
  const pickPlateMode = (m: "core" | "portrait") => {
    localStorage.setItem("eve.plateMode", m);
    setPlateMode(m);
  };
  // Presence-check pills (wardrobe sheet): preview a state, revert after 3.6s.
  const previewTimer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const previewState = (st: EveMode) => {
    if (busy.current || recording) return; // never fight a live turn
    if (previewTimer.current) clearTimeout(previewTimer.current);
    setMode(st);
    if (st !== "idle") previewTimer.current = setTimeout(() => setMode("idle"), 3600);
  };

  const convId = useRef<string | null>(localStorage.getItem(CONV_KEY));
  const busy = useRef(false);
  const abortRef = useRef<AbortController | null>(null);
  const timers = useRef<ReturnType<typeof setTimeout>[]>([]);
  const recorderRef = useRef<MediaRecorder | null>(null);
  const lastInputWasVoice = useRef(false);
  const ttsAvailable = useRef(false);
  const senseHandles = useRef<PluginListenerHandle[]>([]);
  const smsWired = useRef(false);
  const notifWired = useRef(false);
  const msgSeq = useRef(0);
  const scrollRef = useRef<HTMLDivElement | null>(null);
  const inputRef = useRef<HTMLTextAreaElement | null>(null);
  // Auto-scroll law: stay pinned to the newest line unless he has deliberately
  // scrolled up to read history. Any send re-arms the pin — asking her a
  // question IS the intent to watch the answer land.
  const stick = useRef(true);

  const later = (fn: () => void, ms: number) => {
    const id = setTimeout(fn, ms);
    timers.current.push(id);
  };
  const newId = () => `m${++msgSeq.current}`;
  // The input grows to fit the thought, up to the CSS max-height.
  const autoGrow = (el: HTMLTextAreaElement) => {
    el.style.height = "auto";
    el.style.height = `${Math.min(el.scrollHeight, 124)}px`;
  };

  // ---- voice-turn audio focus ----
  // ONE focus session spans the whole spoken exchange: grabbed when he taps the
  // mic (music/YouTube pause while he talks AND while she answers), released
  // once at the definitive end (her reply finishes, or any failure/no-voice
  // path). Idempotent so every terminal branch can call release() safely.
  const voiceFocusHeld = useRef(false);
  const holdVoiceFocus = () => {
    if (!voiceFocusHeld.current) {
      voiceFocusHeld.current = true;
      void requestAudioFocus();
    }
  };
  const releaseVoiceFocus = () => {
    if (voiceFocusHeld.current) {
      voiceFocusHeld.current = false;
      void abandonAudioFocus();
    }
  };

  // ---- her senses (Phase 4, 05 §7): forward texts + notifications to the
  // brain's transient buffers while the app is open. Wiring is idempotent,
  // and nothing here ever PROMPTS — the permission asks live behind the
  // "ENABLE HER SENSES" buttons on the Wire screen (lazy, 05 §7).
  const wireSmsListener = useCallback(async () => {
    if (!smsWired.current) {
      smsWired.current = true;
      senseHandles.current.push(await onSmsReceived((e) => void forwardSms(e)));
    }
    setSmsSense(true);
  }, []);

  const wireNotificationListener = useCallback(async () => {
    if (!notifWired.current) {
      notifWired.current = true;
      senseHandles.current.push(
        await onNotificationPosted((e) => {
          if (e.package === "com.churlish.eve") return; // her own pings — no feedback loop
          void forwardNotification(e);
        }),
      );
    }
    setNotifSense(true);
  }, []);

  const refreshSenses = useCallback(async () => {
    if (!smsSupported()) return;
    // Wire only what's ALREADY granted — never auto-request on boot.
    const { sms } = await checkReadSmsPermissions();
    if (sms === "granted") void wireSmsListener();
    if (await isNotificationAccessEnabled()) void wireNotificationListener();
    else setNotifSense(false); // revoked in settings — show it honestly
  }, [wireSmsListener, wireNotificationListener]);

  useEffect(() => {
    const clock = setInterval(() => setNow(new Date()), 30_000);
    const t = timers.current;
    // FCM registration + deeplink routing (native only; no-op in the browser).
    initPush((deeplink) => {
      if (deeplink === "eve://today") setTab("today");
      else if (deeplink === "eve://ops") setTab("ops");
    });
    // Senses: wire whatever's already granted; re-check with the state poll
    // so flipping notification access in settings lands within a minute.
    void refreshSenses();
    // Her real wardrobe — Brandon's own renders, served by the brain (05 §5).
    // These are HIS uploads: pre-approved by definition; his last worn pick
    // persists locally. Keeps RETRYING with the state poll until the brain
    // answers, so one blip at launch doesn't strip her closet for the session.
    let wardrobeLoaded = false;
    const loadWardrobe = () =>
      fetchWardrobe().then(({ wearing, looks: ws }) => {
        if (!ws.length) return;
        // The brain is the single truth for "wearing" — she changes her own
        // look with wear_look, and King's taps post there too. localStorage
        // is only the pre-brain fallback.
        const worn = wearing ?? localStorage.getItem(WEAR_KEY);
        if (wardrobeLoaded) {
          // Later polls: only sync the worn look (hers may have changed).
          if (worn) {
            setLooks((ls) =>
              ls.some((l) => l.id === worn && l.status !== "wearing")
                ? ls.map((l) => ({
                    ...l,
                    status: l.id === worn ? "wearing" : l.status === "wearing" ? "approved" : l.status,
                  }))
                : ls,
            );
          }
          return;
        }
        wardrobeLoaded = true;
        setLooks(
          ws.map((w) => ({
            id: w.file,
            name: w.name,
            img: wardrobeImgUrl(w),
            status: (worn ? w.file === worn : w.file.toLowerCase() === "base.png") ? "wearing" : "approved",
          })),
        );
      });
    // Live ledger for Today/Ops — refresh every 60s (wardrobe piggybacks
    // until it lands once).
    const loadState = () =>
      fetchState().then((s) => {
        setLive(s);
        ttsAvailable.current = !!s.connectors?.find((c) => c.key === "elevenlabs")?.connected;
        void loadWardrobe(); // cheap JSON; keeps her self-chosen look in sync
        void refreshSenses(); // cheap native checks; never prompts
      });
    loadState();
    loadWardrobe();
    const stateTimer = setInterval(loadState, 60_000);
    return () => {
      clearInterval(clock);
      clearInterval(stateTimer);
      t.forEach(clearTimeout);
      abortRef.current?.abort();
      senseHandles.current.forEach((h) => void h.remove());
    };
  }, []);

  // Keep the newest line in view. Instant, never smooth: at streaming rates a
  // smooth scroll never lands before the next token restarts it, so the view
  // ends up permanently chasing the text instead of sitting on it.
  const pinToBottom = useCallback((force = false) => {
    const el = scrollRef.current;
    if (!el) return;
    if (force) stick.current = true;
    if (!stick.current) return;
    el.scrollTop = el.scrollHeight;
  }, []);

  // He dragged the thread: inside 120px of the floor still counts as watching.
  // 120 is deliberately wider than the 82px the growing textarea can steal
  // (eveStyles.ts:228, 42px -> 124px), so typing can never disarm the pin.
  const onConvScroll = useCallback(() => {
    const el = scrollRef.current;
    if (!el) return;
    stick.current = el.scrollHeight - el.scrollTop - el.clientHeight < 120;
  }, []);

  // (a) The CONTENT grew: his line, her next token, a confirm card.
  useEffect(() => {
    if (tab !== "eve") return;
    pinToBottom();
  }, [messages, tab, confirms.length, pinToBottom]);

  // (b) The BOX shrank — the case the old effect could not see, because none
  // of it touches React state. Two things shrink .conv while he types:
  //   1. the textarea growing to fit a multi-line thought (autoGrow, above;
  //      .inputrow is flex:none so the 82px comes straight out of .conv), and
  //   2. the keyboard opening — adjustResize (AndroidManifest.xml) resizes the
  //      WebView, 100dvh recomputes, and the max-height:640px rules strip the
  //      entity zone / chips / mic row.
  // A ResizeObserver on .conv catches both with one mechanism.
  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const ro = typeof ResizeObserver !== "undefined" ? new ResizeObserver(() => pinToBottom()) : null;
    ro?.observe(el);
    // adjustResize also fires a plain window resize — free insurance for
    // WebViews that coalesce the observer through the IME animation.
    const onResize = () => pinToBottom();
    window.addEventListener("resize", onResize);
    return () => {
      ro?.disconnect();
      window.removeEventListener("resize", onResize);
    };
  }, [tab, pinToBottom]);

  // ---- the live brain call ----
  const runMessage = useCallback(async (text: string, showUser = true, viaVoice = false) => {
    if (busy.current || !text.trim()) return;
    busy.current = true;
    stick.current = true; // every send re-arms the pin, wherever it came from
    lastInputWasVoice.current = viaVoice;
    abortRef.current = new AbortController();
    setErrNote(null);
    setToolNote(null);
    const eveId = newId();
    // Optimistic user line, then an empty EVE line that fills token by token.
    setMessages((ms) => [
      ...ms,
      ...(showUser ? [{ id: newId(), role: "user" as const, text }] : []),
      { id: eveId, role: "eve" as const, text: "" },
    ]);
    setMode("thinking");

    await streamChat(text, convId.current, "app", {
      onState: (s) => {
        if (s === "speaking") setMode("speaking");
        else if (s === "idle") setMode("idle");
      },
      onToken: (tk) =>
        setMessages((ms) => ms.map((m) => (m.id === eveId ? { ...m, text: m.text + tk } : m))),
      onTool: (name) => setToolNote(name),
      onConfirm: (c) => setConfirms((cs) => (cs.some((x) => x.id === c.id) ? cs : [...cs, c])),
      onDone: ({ conversationId, fullText }) => {
        convId.current = conversationId;
        localStorage.setItem(CONV_KEY, conversationId);
        setMode("idle");
        setToolNote(null);
        busy.current = false;
        // Voice loop (05 §3): spoken question → spoken answer. Degrades to
        // text silently when ElevenLabs isn't wired. Audio focus was already
        // grabbed at mic-tap (music/YouTube paused through his question); it
        // stays held across her reply and is released the moment she finishes —
        // or right now if there's no spoken answer to play.
        if (lastInputWasVoice.current && ttsAvailable.current && fullText.trim()) {
          void speakText(fullText).then((url) => {
            if (!url) {
              releaseVoiceFocus(); // TTS failed — don't leave his music paused
              return;
            }
            const audio = new Audio(url);
            let released = false;
            const finish = () => {
              if (!released) {
                released = true;
                releaseVoiceFocus();
              }
              setMode("idle");
              URL.revokeObjectURL(url);
            };
            setMode("speaking");
            audio.onended = finish;
            audio.onerror = finish;
            audio.play().catch(finish);
          });
        } else {
          // Voice in, but no voice out (text-only reply, or TTS off): resume now.
          releaseVoiceFocus();
        }
      },
      onError: (m) => {
        setErrNote(m);
        setMode("idle");
        setToolNote(null);
        busy.current = false;
        releaseVoiceFocus(); // brain failed mid-turn — resume his music
        // Drop the empty shell so a failure never reads as her saying nothing.
        setMessages((ms) => ms.filter((x) => !(x.id === eveId && !x.text)));
      },
    }, abortRef.current.signal);
  }, []);

  const sendText = () => {
    const t = draft.trim();
    if (!t) return;
    setDraft("");
    // setDraft doesn't fire onChange, so the grown height would stick after
    // a multi-line send — collapse it by hand.
    if (inputRef.current) inputRef.current.style.height = "auto";
    runMessage(t);
  };

  // ---- RED-tier confirm resolution ----
  const decideConfirm = async (c: PendingConfirm, approve: boolean) => {
    setConfirmNote((n) => ({ ...n, [c.id]: "…" }));
    const r = await resolveConfirm(c.id, c.hash, approve);
    let note: string;
    if (r.ok && r.clientAction?.type === "send_sms") {
      // SMS leaves from HIS SIM (02 §6 / 05 §7): the brain approved the exact
      // payload; this phone transmits it. Only reachable through an explicit
      // approve — the ONLY path that ever calls sendSms.
      const p = r.clientAction.payload as { phoneNumber: string; message: string };
      try {
        let { sms } = await checkSendSmsPermissions();
        if (sms !== "granted") ({ sms } = await requestSendSmsPermissions());
        if (sms !== "granted") throw new Error("SEND_SMS permission denied");
        await sendSms({ phoneNumber: p.phoneNumber, message: p.message });
        void reportSmsSent(p.phoneNumber, p.message);
        note = "SENT from your phone";
      } catch (err) {
        note = `FAILED — ${err instanceof Error ? err.message : "send error"}`;
      }
    } else {
      note = r.ok ? (r.executed ? `SENT — ${r.detail ?? ""}` : "CANCELLED") : `FAILED — ${r.error ?? "unknown"}`;
    }
    setConfirmNote((n) => ({ ...n, [c.id]: note }));
    later(() => {
      setConfirms((cs) => cs.filter((x) => x.id !== c.id));
      setConfirmNote((n) => {
        const { [c.id]: _gone, ...rest } = n;
        return rest;
      });
    }, 5000);
    fetchState().then(setLive);
  };

  // ---- her senses: the lazy permission asks (Wire screen buttons) ----
  const enableSmsSense = async () => {
    const { sms } = await requestReadSmsPermissions();
    if (sms === "granted") void wireSmsListener();
  };
  const enableNotifSense = async () => {
    // Notification access is a settings toggle, not a runtime prompt: send
    // him there; the state poll wires the listener once he flips it on.
    if (await isNotificationAccessEnabled()) return void wireNotificationListener();
    await openNotificationAccessSettings();
  };

  // ---- Ops actions (approve / hold / dismiss) ----
  const opsAction = async (id: string, action: "approve" | "hold" | "dismiss") => {
    setOpsBusy(id);
    await actOnAttention(id, action);
    setOpsBusy(null);
    fetchState().then(setLive);
  };

  // ---- § RUN HER DAY: fires her REAL morning brief, not a scripted preview ----
  const runHerDay = async () => {
    if (jobBusy) return;
    setJobBusy(true);
    setJobNote(null);
    const r = await runJob("morning_brief", true);
    setJobNote(
      r.ok
        ? "BRIEF GENERATED — IT'S THE LINE AT THE TOP OF THIS SCREEN"
        : `NO BRIEF — ${(r.reason ?? r.error ?? "the brain declined").toUpperCase()}`,
    );
    setJobBusy(false);
    fetchState().then(setLive);
    later(() => setJobNote(null), 9000);
  };

  const wake = () => {
    setBootLeaving(true);
    later(() => {
      setBooted(true);
      setTab("eve");
      // Generated greeting — not a canned string. Seed is a system event, not shown.
      runMessage("[King just opened the app. Greet him and give a short read on the moment.]", false);
    }, 480);
  };

  // Voice in (05 §3): tap to record, tap to stop → Deepgram via the brain →
  // the transcript goes through the normal chat loop.
  const micTap = async () => {
    if (recording) {
      recorderRef.current?.stop();
      return;
    }
    const sttReady = live.connectors?.find((c) => c.key === "deepgram")?.connected;
    if (!sttReady) {
      setMicNote(true);
      later(() => setMicNote(false), 2600);
      return;
    }
    try {
      const stream = await navigator.mediaDevices.getUserMedia({ audio: true });
      const mime = MediaRecorder.isTypeSupported("audio/webm;codecs=opus")
        ? "audio/webm;codecs=opus"
        : MediaRecorder.isTypeSupported("audio/mp4")
          ? "audio/mp4"
          : "";
      const rec = new MediaRecorder(stream, mime ? { mimeType: mime } : undefined);
      const chunks: Blob[] = [];
      rec.ondataavailable = (e) => {
        if (e.data.size > 0) chunks.push(e.data);
      };
      rec.onstop = async () => {
        stream.getTracks().forEach((tr) => tr.stop());
        setRecording(false);
        setMode("thinking");
        const blob = new Blob(chunks, { type: mime || "audio/webm" });
        const r = await transcribeAudio(blob);
        if (r.ok && r.transcript?.trim()) {
          // Keep the audio focus held — runMessage releases it when her reply ends.
          runMessage(r.transcript, true, true);
        } else {
          releaseVoiceFocus(); // nothing to say back — resume his music
          setMode("idle");
          setErrNote(r.error || "didn't catch that — try again");
        }
      };
      recorderRef.current = rec;
      rec.start();
      setRecording(true);
      setMode("listening");
      // Pause his music/YouTube the moment she starts listening, so the mic
      // isn't recording over them and the whole exchange is clean.
      holdVoiceFocus();
    } catch {
      releaseVoiceFocus();
      setErrNote("microphone unavailable — check the permission");
    }
  };

  const wearing = looks.find((l) => l.status === "wearing") ?? null;
  const wear = (id: string) => {
    localStorage.setItem(WEAR_KEY, id);
    void postWear(id);
    setLooks((ls) =>
      ls.map((l) => ({
        ...l,
        status: l.id === id ? "wearing" : l.status === "wearing" ? "approved" : l.status,
      })),
    );
  };

  // ---- clock / date (v6 status bar format: 14:07 · THU 17 JUL) ----
  const pad = (n: number) => String(n).padStart(2, "0");
  const clockStr = `${pad(now.getHours())}:${pad(now.getMinutes())}`;
  const dateStr = `${now.toLocaleDateString("en-GB", { weekday: "short" }).toUpperCase()} ${pad(now.getDate())} ${now.toLocaleDateString("en-GB", { month: "short" }).toUpperCase()}`;
  const weekNo = Math.ceil(
    ((now.getTime() - new Date(now.getFullYear(), 0, 1).getTime()) / 86400000 +
      new Date(now.getFullYear(), 0, 1).getDay() +
      1) /
      7,
  );
  const greeting =
    (now.getHours() < 5 ? "Late shift, " : now.getHours() < 12 ? "Morning, " : now.getHours() < 18 ? "Afternoon, " : "Evening, ") +
    "Brandon.";

  // ---- ops slicing ----
  const pendings = live.online ? live.pendingConfirms ?? [] : [];
  const attention = live.online ? live.attentionItems ?? [] : [];
  const tripwires = attention.filter((a) => a.kind === "tripwire");
  const inbox = attention.filter((a) => a.kind !== "tripwire");
  const quietCount = (live.clients ?? []).filter(
    (c) => c.days_quiet !== null && c.days_quiet > c.cadence_days,
  ).length;
  const jobCode = (agent: string) =>
    ({ eve: "EV", research: "RS", jsa: "JS", "justice-league": "JL", "suicide-squad": "SQ" })[agent] ??
    agent.slice(0, 2).toUpperCase();
  const aGlyph = (kind: string) =>
    kind === "silent_client" ? "@" : kind === "approval" ? "▸" : kind === "inbox" ? "+" : "•";

  // ---- wire nodes (honest status; only what's wired reads LIVE) ----
  const conn = (k: string) => !!live.connectors?.find((c) => c.key === k)?.connected;
  type WNode = { code: string; name: string; role: string; st: "live" | "key" | "off" | "p4" };
  const wireNodes: WNode[] = [
    { code: "EV", name: "EVE Brain", role: "reasoning core", st: live.online ? "live" : "off" },
    { code: "SB", name: "Supabase", role: "memory · ledgers", st: live.online ? "live" : "off" },
    { code: "GM", name: "Gmail", role: "read · draft · send", st: conn("gmail") ? "live" : "key" },
    { code: "CL", name: "Calendar", role: "clocks · windows", st: conn("gcal") ? "live" : "key" },
    { code: "OS", name: "Churlish OS", role: "board · pennyworth", st: conn("churlish_os") ? "live" : "key" },
    { code: "DG", name: "Deepgram", role: "her ears", st: conn("deepgram") ? "live" : "key" },
    { code: "11", name: "ElevenLabs", role: "her voice", st: conn("elevenlabs") ? "live" : "key" },
    { code: "FL", name: "EVE Fleet", role: "research · tribunals", st: live.online ? "live" : "off" },
    { code: "WB", name: "Live Web", role: "search · sources", st: live.online ? "live" : "off" },
    { code: "G2", name: "G2 Glasses", role: "her eyes · someday", st: "p4" },
  ];
  const liveNodeCount = wireNodes.filter((w) => w.st === "live").length;
  const sttOn = conn("deepgram");
  const ttsOn = conn("elevenlabs");

  // Portrait vs core: his sheet toggle wins; otherwise her worn look decides.
  const showPortrait = (plateMode ?? (wearing ? "portrait" : "core")) === "portrait" && !!wearing?.img;
  const ent = ENT[mode];
  const red = mode === "alert";
  const voiceLine = recording
    ? "LISTENING —\nTAP TO SEND"
    : micNote
      ? "EARS NEED\nTHE KEY"
      : mode === "thinking"
        ? "PARSING…"
        : mode === "speaking"
          ? "SYNTHESISING"
          : `${sttOn ? "DEEPGRAM ● LIVE" : "EARS — KEY NEEDED"}\n${ttsOn ? "VOICE: LARA" : "VOICE — KEY NEEDED"}`;

  const orbEl = (
    <div className="ezone">
      <div className="eaura" style={{ background: `radial-gradient(closest-side, ${ent.aura}, transparent 70%)` }} />
      {mode === "listening" && (
        <>
          <span className="erip" />
          <span className="erip r2" />
          <span className="erip r3" />
        </>
      )}
      <div className="ering"><div style={red ? { borderColor: "rgba(196,30,58,.55)", borderBottomColor: "transparent" } : undefined} /></div>
      <div className="ering2"><div style={red ? { borderColor: "rgba(196,30,58,.4)", borderTopColor: "transparent" } : undefined} /></div>
      <div className={`efast${mode === "thinking" ? " on" : ""}`}><div /></div>
      <button
        className="orb"
        aria-label="EVE core — open wardrobe"
        onClick={() => setWardrobe(true)}
        style={{ background: red ? ORB_BG_RED : ORB_BG, boxShadow: red ? ORB_GLOW_RED : ORB_GLOW }}
      />
      {mode === "speaking" && (
        <div className="ewave"><span /><span /><span /><span /><span /></div>
      )}
    </div>
  );

  const portraitEl = wearing?.img && (
    <div className="pwrap">
      <div className="eaura" style={{ background: `radial-gradient(closest-side, ${ent.aura}, transparent 70%)` }} />
      <button className="pcard" aria-label="Open wardrobe" onClick={() => setWardrobe(true)}>
        <span className="pc tl" /><span className="pc tr" /><span className="pc bl" /><span className="pc br" />
        <span className={`pfr${red ? " alert" : ""}`}>
          <img src={wearing.img} alt={`EVE — ${wearing.name}`} />
          <span className="sheen" />
        </span>
      </button>
      <div className="pbadge">
        <span className="wm">EVE</span>
        <span className="dv" />
        <span className="sb">{wearing.name.toUpperCase()}</span>
        <span
          className="morb"
          style={{ background: red ? ORB_BG_RED : ORB_BG, boxShadow: red ? "0 0 12px rgba(196,30,58,.6)" : "0 0 12px rgba(28,185,200,.6)" }}
        />
      </div>
    </div>
  );

  return (
    <div className="eve-root">
      <style>{CSS}</style>
      <div className="eve-frame">
        <div className="aura" />
        <div className="motes" aria-hidden>
          <span style={{ left: "14%", top: "78%", width: 2, height: 2, animation: "floatup 13s linear 0s infinite" }} />
          <span style={{ left: "30%", top: "88%", width: 3, height: 3, opacity: .6, animation: "floatup 17s linear 3s infinite" }} />
          <span style={{ left: "48%", top: "82%", width: 2, height: 2, background: "rgba(155,239,247,.45)", animation: "floatup 11s linear 6s infinite" }} />
          <span style={{ left: "63%", top: "90%", width: 2, height: 2, animation: "floatup 15s linear 1.5s infinite" }} />
          <span style={{ left: "78%", top: "80%", width: 3, height: 3, opacity: .5, animation: "floatup 19s linear 8s infinite" }} />
          <span style={{ left: "88%", top: "86%", width: 2, height: 2, background: "rgba(155,239,247,.35)", animation: "floatup 14s linear 4.5s infinite" }} />
        </div>

        {/* ---------- status bar ---------- */}
        <div className="sbar">
          <span>{clockStr} · {dateStr}</span>
          <span className="r">
            <span>EVE//OS {APP_VERSION}</span>
            <span className={`lnk${live.online ? "" : " down"}`}>●</span>
            <span className={`lnklab${live.online ? "" : " down"}`}>{live.online ? "LINK" : "DOWN"}</span>
          </span>
        </div>

        <div className="zone">
          {/* ---------- TODAY ---------- */}
          {tab === "today" && (
            <div className="scr">
              <div className="eyeb mono">
                <span>▸ EVE//BRIEF — {dateStr} · WK {weekNo}</span>
                <span className="r">REFRESHED {clockStr}</span>
              </div>
              <h1 className="h1v6 disp">{greeting}</h1>
              <p className="ledev6">
                {live.online && live.latestBrief?.text
                  ? live.latestBrief.text
                  : live.online
                    ? "No brief on the board yet. Run her day below, or just tell her what matters."
                    : "Her brain is unreachable, so this screen is a shell. It fills in the moment she answers."}
              </p>

              {/* sales floor */}
              <div className="card" style={{ marginTop: 22 }}>
                <div className="eyeb mono" style={{ fontSize: 9 }}>
                  <span>SALES FLOOR — WEEK {weekNo}</span>
                  <span className="r">FLOOR: {live.floor?.goal ?? 3} / WK</span>
                </div>
                <div style={{ display: "flex", alignItems: "baseline", gap: 10, marginTop: 10 }}>
                  <span className="floorbig disp">
                    {live.floor?.count ?? 0}
                    <em>/{live.floor?.goal ?? 3}</em>
                  </span>
                  <span style={{ fontSize: 13, color: "rgba(240,237,232,.55)" }}>conversations on the floor</span>
                </div>
                <div className="fbars">
                  {Array.from({ length: live.floor?.goal ?? 3 }).map((_, i) => (
                    <span key={i} className={(live.floor?.count ?? 0) > i ? "on" : ""} />
                  ))}
                </div>
                <div className="mline">
                  {live.online
                    ? `> ${Math.max(0, (live.floor?.goal ?? 3) - (live.floor?.count ?? 0))} to go — real conversations, not drafts.`
                    : "> offline — the count lands when her brain answers."}
                </div>
              </div>

              {/* today's three */}
              <div className="divrow">
                <span className="l">TODAY'S THREE</span>
                <span className="rule" />
                <span className="r">{live.todaysThree?.length ? "SHE SET THE ORDER" : ""}</span>
              </div>
              <div className="t3">
                {live.todaysThree?.length ? (
                  live.todaysThree.map((t) => {
                    const due = !!t.due_at && new Date(t.due_at).getTime() < now.getTime();
                    return (
                      <div className={`t3row${due ? " due" : ""}`} key={t.id}>
                        <span className="idx mono">{String(t.priority).padStart(2, "0")}</span>
                        <span style={{ flex: 1 }}>
                          <span className="tt">{t.title}</span>
                          {t.detail && <span className="tm" style={{ display: "block" }}>{t.detail.toUpperCase()}</span>}
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <div className="t3row">
                    <span className="idx mono">—</span>
                    <span style={{ flex: 1 }}>
                      <span className="tt">{live.online ? "Nothing set yet" : "Waiting on her brain"}</span>
                      <span className="tm" style={{ display: "block" }}>
                        {live.online ? "TELL HER WHAT MATTERS — SHE'LL SLOT IT" : "ARRIVES WITH THE NEXT POLL"}
                      </span>
                    </span>
                  </div>
                )}
              </div>

              {/* run her day — the REAL morning brief, not a scripted preview */}
              <div className="card" style={{ marginTop: 22, borderColor: "rgba(28,185,200,.14)" }}>
                <div className="simhead">
                  <button className="simplay" onClick={runHerDay} disabled={jobBusy || !live.online} aria-label="Run her morning brief now">
                    <svg viewBox="0 0 24 24" style={{ width: 18, height: 18, fill: "#9BEFF7" }}><path d="M8 5.5l11 6.5-11 6.5z" /></svg>
                  </button>
                  <div style={{ flex: 1 }}>
                    <div className="simtt disp">Run EVE's day</div>
                    <div className="simsub">Fires her real morning brief, right now, on live data.</div>
                  </div>
                  <span className="simtag mono">LIVE // BRIEF</span>
                </div>
                <div className="simbar">
                  <div className={`simfill${jobBusy ? " run" : ""}`} style={{ width: jobBusy ? undefined : jobNote ? "100%" : "0%" }} />
                </div>
                <div className="simline mono">
                  {jobBusy ? (
                    <>
                      {"> she's writing it now"}
                      <span className="c">▌</span>
                    </>
                  ) : jobNote ? (
                    `> ${jobNote.toLowerCase()}`
                  ) : live.online ? (
                    "> press play. she writes. you drink your coffee."
                  ) : (
                    "> needs her brain — currently unreachable."
                  )}
                </div>
              </div>

              {/* capture */}
              <div className="card" style={{ marginTop: 22 }}>
                <div className="mono" style={{ fontSize: 9, letterSpacing: ".22em", color: "rgba(28,185,200,.85)" }}>
                  CAPTURE — ANY DOOR IN
                </div>
                <div
                  className="capbox"
                  role="button"
                  tabIndex={0}
                  onClick={() => setTab("eve")}
                  onKeyDown={(e) => { if (e.key === "Enter") setTab("eve"); }}
                >
                  <span className="ph mono">&gt; brief me — say it, type it, forward it.</span>
                  <svg viewBox="0 0 24 24" style={{ width: 16, height: 16, fill: "none", stroke: "rgba(28,185,200,.8)", strokeWidth: 1.6, strokeLinecap: "round" }}>
                    <rect x="9" y="3" width="6" height="11" rx="3" /><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0" /><path d="M12 18v3" />
                  </svg>
                </div>
                <div className="caphint mono">SPEAK · TYPE · FORWARD — SHE FILES, YOU FORGET.</div>
              </div>

              {/* live minis */}
              <div className="minis">
                <div className="mini">
                  <div className="k mono">ROUTINES</div>
                  <div className="n disp">{live.routines?.length ?? 0}</div>
                  <div className="s mono">
                    {live.routines?.length
                      ? `best streak ${Math.max(...live.routines.map((r) => r.streak))}d`
                      : live.online
                        ? "none tracked yet"
                        : "—"}
                  </div>
                  {live.routines?.slice(0, 1).map((r) => (
                    <div className="x mono" key={r.id}>{r.name} — {r.streak}d</div>
                  ))}
                </div>
                <div className="mini">
                  <div className="k mono">CLIENT PULSE</div>
                  <div className="n disp">
                    {live.clients?.length ?? 0}
                    <em> roster</em>
                  </div>
                  <div className="s mono">{live.online ? `${quietCount} past cadence` : "—"}</div>
                  <div className="x mono">{quietCount > 0 ? "she has updates drafted" : "all inside the window"}</div>
                </div>
              </div>

              <div className="footnote mono">up since 05:30 so you didn't have to be.</div>
            </div>
          )}

          {/* ---------- EVE / TALK ---------- */}
          {tab === "eve" && (
            <div className="scr talk">
              <div className="ehead">
                <div className="etag mono">EVE // EXECUTIVE VOICE ENGINE</div>
                {showPortrait ? portraitEl : orbEl}
                <div className="elabel mono" style={{ color: ent.col }}>
                  {ent.dot} {ent.label}
                  {toolNote ? ` · ${toolNote.replace(/_/g, " ").toUpperCase()}` : ""}
                </div>
              </div>

              <div className="conv" ref={scrollRef} onScroll={onConvScroll}>
                {messages.length === 0 && (
                  <div className="brow eve">
                    <div className="bub eve">
                      <div className="bname mono">EVE</div>
                      <div className="btext" style={{ color: "rgba(240,237,232,.5)" }}>
                        Type below, talk, or pick a prompt. Every line is written live — real replies, real memory.
                      </div>
                    </div>
                  </div>
                )}
                {messages.map((m) =>
                  m.role === "eve" ? (
                    <div className="brow eve" key={m.id}>
                      <div className="bub eve">
                        <div className="bname mono">EVE</div>
                        {m.text ? (
                          <div className="btext" dangerouslySetInnerHTML={{ __html: mdLite(m.text) }} />
                        ) : mode === "thinking" ? (
                          <div style={{ display: "flex", gap: 5, padding: "3px 0" }}>
                            <span style={{ width: 4, height: 4, borderRadius: "50%", background: "#1CB9C8", animation: "typedot 1.1s ease-in-out 0s infinite" }} />
                            <span style={{ width: 4, height: 4, borderRadius: "50%", background: "#1CB9C8", animation: "typedot 1.1s ease-in-out .18s infinite" }} />
                            <span style={{ width: 4, height: 4, borderRadius: "50%", background: "#1CB9C8", animation: "typedot 1.1s ease-in-out .36s infinite" }} />
                          </div>
                        ) : (
                          <div className="btext" />
                        )}
                      </div>
                    </div>
                  ) : (
                    <div className="brow you" key={m.id}>
                      <div className="bub you">
                        <div className="bname mono">YOU</div>
                        <div className="btext">{m.text}</div>
                      </div>
                    </div>
                  ),
                )}
                {errNote && <div className="errline mono">LINK: {errNote}</div>}

                {/* RED-tier confirm cards (02 §6): exact payload + approve round-trip */}
                {confirms.map((c) => (
                  <div className="confirmv6" key={c.id}>
                    <div className="hd mono">▲ RED TIER · {c.kind.replace(/_/g, " ").toUpperCase()} — NOTHING SENDS WITHOUT YOU</div>
                    <div className="sum">{c.summary}</div>
                    {Object.entries(c.payload).map(([k, v]) => (
                      <div className="field" key={k}>
                        <b>{k.toUpperCase()}</b>
                        {String(v).slice(0, 240)}
                      </div>
                    ))}
                    {confirmNote[c.id] ? (
                      <div className={`cnote6${confirmNote[c.id].startsWith("SENT") ? " ok" : ""}`}>{confirmNote[c.id]}</div>
                    ) : (
                      <div className="row">
                        <button className="cbtn ok hit44" onClick={() => decideConfirm(c, true)}>APPROVE — SEND IT</button>
                        <button className="cbtn gh hit44" onClick={() => decideConfirm(c, false)}>CANCEL</button>
                      </div>
                    )}
                  </div>
                ))}
              </div>

              <div className="chiprow">
                {CHIPS.map((c) => (
                  <button key={c} className="chipv6" disabled={mode !== "idle"} onClick={() => runMessage(c)}>
                    {c}
                  </button>
                ))}
              </div>

              <div className="inputrow">
                <textarea
                  className="tinv6"
                  ref={inputRef}
                  rows={1}
                  value={draft}
                  onChange={(e) => {
                    setDraft(e.target.value);
                    autoGrow(e.target);
                  }}
                  onKeyDown={(e) => {
                    if (e.key === "Enter" && !e.shiftKey) {
                      e.preventDefault();
                      sendText();
                    }
                  }}
                  onFocus={() => {
                    // The IME animates in over ~250ms and adjustResize lands the
                    // new viewport somewhere mid-animation. Pin across it so the
                    // newest line is under his thumb when it settles.
                    pinToBottom(true);
                    later(() => pinToBottom(true), 150);
                    later(() => pinToBottom(true), 400);
                  }}
                  placeholder="Type to her — or just talk."
                  aria-label="Message EVE"
                />
                <button className="sendv6 hit44" onClick={sendText} aria-label="Send">
                  <svg viewBox="0 0 20 20" style={{ width: 17, height: 17, fill: "none", stroke: "#9BEFF7", strokeWidth: 1.6, strokeLinecap: "round", strokeLinejoin: "round" }}>
                    <path d="M3 10h13" /><path d="M11.5 4.5L17 10l-5.5 5.5" />
                  </svg>
                </button>
              </div>

              <div className="microw">
                <div className={`vline mono${recording ? " rec" : ""}`}>{voiceLine}</div>
                <button
                  className={`micv6${recording ? " rec" : mode === "listening" ? " on" : ""}`}
                  onClick={micTap}
                  aria-label={recording ? "Stop and send" : "Talk to EVE"}
                >
                  <svg viewBox="0 0 24 24" style={{ width: 22, height: 22, fill: "none", stroke: recording ? "#F7C9D2" : "#1CB9C8", strokeWidth: 1.6, strokeLinecap: "round" }}>
                    <rect x="9" y="3" width="6" height="11" rx="3" /><path d="M5.5 11.5a6.5 6.5 0 0 0 13 0" /><path d="M12 18v3" />
                  </svg>
                </button>
                <button className="wbtn" onClick={() => setWardrobe(true)}>[ WARDROBE ]</button>
              </div>
              <div className="footline mono">push-to-talk only. she never listens uninvited.</div>
            </div>
          )}

          {/* ---------- OPS ---------- */}
          {tab === "ops" && (
            <div className="scr">
              <div className="eyeb mono">
                <span>▸ OPERATIONS // THE FLEET</span>
                <span className="r">{live.online ? "REPORTING LIVE" : "OFFLINE"}</span>
              </div>
              <h1 className="h1v6 disp">OPS</h1>
              <p className="ledev6">Your signature, not your time.</p>

              {/* RED tier — waiting on your thumb (02 §6) */}
              {!!pendings.length && (
                <>
                  <div className="divrow">
                    <span className="l" style={{ color: "#C41E3A" }}>WAITING ON YOUR THUMB — RED</span>
                    <span className="rule" />
                    <span className="r">{pendings.length}</span>
                  </div>
                  {pendings.map((c) => (
                    <div className="confirmv6" style={{ marginBottom: 8 }} key={c.id}>
                      <div className="sum">{c.summary}</div>
                      <div className="field">
                        expires {new Date(c.expiresAt).toLocaleTimeString("en-US", { hour: "numeric", minute: "2-digit" })}
                      </div>
                      {confirmNote[c.id] ? (
                        <div className="cnote6">{confirmNote[c.id]}</div>
                      ) : (
                        <div className="row">
                          <button className="cbtn ok hit44" onClick={() => decideConfirm(c, true)}>APPROVE</button>
                          <button className="cbtn gh hit44" onClick={() => decideConfirm(c, false)}>CANCEL</button>
                        </div>
                      )}
                    </div>
                  ))}
                </>
              )}

              <div className="divrow">
                <span className="l">JOBS IN FLIGHT</span>
                <span className="rule" />
                <span className="r">{live.jobs?.length ? `${live.jobs.length} ACTIVE` : "IDLE"}</span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {live.jobs?.length ? (
                  live.jobs.map((j) => (
                    <div className="jobrow6" key={j.id}>
                      <span className="jcode mono">{jobCode(j.agent || "eve")}</span>
                      <span className="jmain">
                        <span className="jname">{j.agent || "eve"}</span>
                        <span className="jtask mono">{j.title}</span>
                      </span>
                      <span className={`jtag mono ${j.status === "running" ? "run" : j.status === "in_approvals" ? "appr" : "que"}`}>
                        {j.status === "running" ? "● RUNNING" : j.status.replace(/_/g, " ").toUpperCase()}
                      </span>
                    </div>
                  ))
                ) : (
                  <div className="secnote6">
                    {live.online
                      ? "Nothing in flight. Give her the job — by name or just the outcome."
                      : "Offline — the fleet reports in when her brain answers."}
                  </div>
                )}
              </div>

              <div className="divrow">
                <span className="l">APPROVAL INBOX</span>
                <span className="rule" />
                <span className="r">{inbox.length ? `${inbox.length} WAITING` : "CLEAR ✓"}</span>
              </div>
              <div style={{ display: "flex", flexDirection: "column", gap: 8 }}>
                {inbox.length ? (
                  inbox.slice(0, 8).map((a) => (
                    <div className="aprow" key={a.id}>
                      <span className="aglyph mono">{aGlyph(a.kind)}</span>
                      <span className="amain">
                        <span className="atitle">{a.message}</span>
                        <span className="asub mono">
                          {a.kind.replace(/_/g, " ").toUpperCase()} · N{a.nudge_level}
                          {a.kind === "silent_client" && a.ref?.draft ? " · DRAFT READY" : ""}
                        </span>
                      </span>
                      {opsBusy === a.id ? (
                        <span className="cnote6">…</span>
                      ) : (
                        <span className="abtns">
                          <button className="cbtn ok hit44" onClick={() => opsAction(a.id, "approve")}>APPROVE</button>
                          <button className="cbtn gh hit44" onClick={() => opsAction(a.id, "hold")}>HOLD</button>
                          <button className="cbtn gh hit44" aria-label="Dismiss" onClick={() => opsAction(a.id, "dismiss")}>✕</button>
                        </span>
                      )}
                    </div>
                  ))
                ) : (
                  <div className="secnote6">
                    {live.online ? "Nothing needs you. She'll surface it here when it does." : "Offline — nothing to show until her brain answers."}
                  </div>
                )}
              </div>

              <div className="divrow">
                <span className="l">CLIENT PULSE</span>
                <span className="rule" />
                <span className="r">{live.online ? `${quietCount} QUIET` : "OFFLINE"}</span>
              </div>
              <div className="pulcard">
                {live.clients?.length ? (
                  live.clients.map((cl) => {
                    const hot = cl.days_quiet !== null && cl.days_quiet > cl.cadence_days;
                    return (
                      <div className="pulrow" key={cl.id}>
                        <span className="pulname">{cl.name}</span>
                        <span className={`puldays mono${hot ? " hot" : ""}`}>
                          {cl.days_quiet === null ? "NEW" : `${cl.days_quiet}D QUIET`}
                        </span>
                        <span className="pulsay">
                          cadence {cl.cadence_days}d{hot ? " — past it. update drafted." : " — inside the window."}
                        </span>
                      </div>
                    );
                  })
                ) : (
                  <div className="pulrow">
                    <span className="pulsay">
                      {live.online ? "No clients in the ledger yet — add them and she starts watching cadences." : "Offline — the radar lands when her brain answers."}
                    </span>
                  </div>
                )}
              </div>

              {tripwires.map((a) => (
                <div className="trip6" key={a.id}>
                  <div className="hd mono">
                    <span>▲ TRIPWIRE — LIVE</span>
                    <span style={{ flex: 1 }} />
                    {opsBusy === a.id ? (
                      <span className="cnote6">…</span>
                    ) : (
                      <span className="abtns">
                        <button className="cbtn ok" onClick={() => opsAction(a.id, "approve")}>APPROVE</button>
                        <button className="cbtn gh" onClick={() => opsAction(a.id, "hold")}>HOLD</button>
                        <button className="cbtn gh" aria-label="Dismiss" onClick={() => opsAction(a.id, "dismiss")}>✕</button>
                      </span>
                    )}
                  </div>
                  <div className="tt">{a.message}</div>
                </div>
              ))}

              <div className="footnote mono">the fleet works. you sign.</div>
            </div>
          )}

          {/* ---------- WIRE ---------- */}
          {tab === "wire" && (
            <div className="scr">
              <div className="eyeb mono">
                <span>▸ CONNECTIONS // {wireNodes.length} NODES</span>
                <span className="r">{liveNodeCount} LIVE</span>
              </div>
              <h1 className="h1v6 disp">WIRE</h1>
              <p className="ledev6">One face. The whole fleet behind it. Only what's wired reads LIVE.</p>

              <div className="wgrid6">
                {wireNodes.map((w) => (
                  <div className={`wnode${w.st === "p4" ? " dash" : w.st === "off" ? " dim" : ""}`} key={w.code}>
                    <div className="top">
                      <span className="wcode mono">{w.code}</span>
                      <span className={`wdot ${w.st === "live" ? "live" : w.st === "key" ? "key" : "off"}`}>
                        {w.st === "p4" ? "◌" : w.st === "off" ? "○" : "●"}
                      </span>
                    </div>
                    <div className="wname6">{w.name}</div>
                    <div className="wrole mono">{w.role}</div>
                    <div className={`wstat mono ${w.st}`}>
                      {w.st === "live" ? "LIVE" : w.st === "key" ? "KEY NEEDED" : w.st === "off" ? "OFFLINE" : "PHASE 5"}
                    </div>
                  </div>
                ))}
              </div>

              {/* HER SENSES (Phase 4, 05 §7): lazy permission asks — prompts fire
                  from THESE taps, never on boot. */}
              <div className="sensecard">
                <div className="hd mono">ENABLE HER SENSES</div>
                <div className="bd">
                  Texts and notifications forward to her brain only while the app is open — transient, never
                  long-term memory. Replies always go through your thumb.
                </div>
                {smsSupported() ? (
                  <div className="sensebtns">
                    <button className={`sense6 hit44${smsSense ? " on" : ""}`} disabled={smsSense} onClick={enableSmsSense}>
                      {smsSense ? "SMS — LIVE" : "[ SMS ]"}
                    </button>
                    <button className={`sense6 hit44${notifSense ? " on" : ""}`} disabled={notifSense} onClick={enableNotifSense}>
                      {notifSense ? "NOTIFICATIONS — LIVE" : "[ NOTIFICATIONS ]"}
                    </button>
                  </div>
                ) : (
                  <div className="caphint mono" style={{ marginTop: 10 }}>
                    ANDROID BUILD ONLY — THE BROWSER HAS NO SMS OR NOTIFICATION ACCESS
                  </div>
                )}
              </div>

              <div className="card rules" style={{ marginTop: 14 }}>
                <div className="mono" style={{ fontSize: 9, letterSpacing: ".22em", color: "rgba(28,185,200,.85)" }}>
                  AUTONOMY — HOUSE RULES
                </div>
                <div className="rulerow">
                  <span className="dot" style={{ background: "#3EA26E", boxShadow: "0 0 8px rgba(62,162,110,.5)" }} />
                  <span className="k mono" style={{ color: "#3EA26E" }}>GREEN</span>
                  <span className="v">Acts, then tells you. Filing, drafts, research, the OS board.</span>
                </div>
                <div className="rulerow">
                  <span className="dot" style={{ background: "#C9A54A", boxShadow: "0 0 8px rgba(201,165,74,.5)" }} />
                  <span className="k mono" style={{ color: "#C9A54A" }}>YELLOW</span>
                  <span className="v">Drafts, then waits. Anything a client will read.</span>
                </div>
                <div className="rulerow">
                  <span className="dot" style={{ background: "#C41E3A", boxShadow: "0 0 8px rgba(196,30,58,.5)" }} />
                  <span className="k mono" style={{ color: "#C41E3A" }}>RED</span>
                  <span className="v">Never without you. Money out, sends, anything public.</span>
                </div>
              </div>

              <div className="footnote mono">she only sees what you hand her. keys stay in your vault.</div>
            </div>
          )}
        </div>

        {/* ---------- wardrobe sheet ---------- */}
        {wardrobe && <div className="scrim6" onClick={() => setWardrobe(false)} />}
        {wardrobe && (
          <div className="sheet6">
            <div className="grab6" />
            <div className="shead">
              <div style={{ flex: 1 }}>
                <div className="lab mono">WARDROBE // PRESENCE</div>
                <div className="tt disp">How she shows up.</div>
              </div>
              <button className="sclose mono" onClick={() => setWardrobe(false)}>[ CLOSE ]</button>
            </div>

            <div className="modes">
              <button className={`modec${!showPortrait ? " on" : ""}`} onClick={() => pickPlateMode("core")}>
                <span className="sw" />
                <span className="k mono">CORE</span>
                <span className="s mono">the pure signal</span>
              </button>
              <button
                className={`modec${showPortrait ? " on" : ""}`}
                onClick={() => pickPlateMode("portrait")}
                disabled={!wearing?.img}
              >
                <span className="sw" style={{ borderRadius: 8, background: wearing?.img ? `url(${wearing.img}) center 12%/cover` : "rgba(28,185,200,.2)" }} />
                <span className="k mono">PORTRAIT</span>
                <span className="s mono">{wearing?.img ? "her face, her look" : "closet loading…"}</span>
              </button>
            </div>

            <div className="divrow" style={{ margin: "18px 0 4px" }}>
              <span className="l">HER CLOSET — {looks.length} LOOKS, HERS TO CHOOSE</span>
              <span className="rule" />
            </div>
            {looks.length ? (
              <div className="lgrid">
                {looks.map((l) => (
                  <button
                    className={`lookc${l.status === "wearing" ? " on" : ""}`}
                    key={l.id}
                    onClick={() => {
                      wear(l.id);
                      if (plateMode === "core") pickPlateMode("portrait");
                    }}
                    aria-label={`Wear ${l.name}`}
                    aria-pressed={l.status === "wearing"}
                  >
                    {l.img && (
                      <span className="thumb">
                        <img src={l.img} alt={l.name} loading="lazy" />
                      </span>
                    )}
                    <span className="nm" style={{ display: "block" }}>{l.name}</span>
                  </button>
                ))}
              </div>
            ) : (
              <p className="secnote6" style={{ marginTop: 10 }}>
                Her closet lives on the brain — currently unreachable. It'll be here the moment she answers.
              </p>
            )}

            <div className="divrow" style={{ margin: "18px 0 10px" }}>
              <span className="l">VOICE — ELEVENLABS</span>
              <span className="rule" />
            </div>
            <span className="vchip mono">{ttsOn ? "LARA — HER PICK" : "AWAITING KEY"}</span>

            <div className="divrow" style={{ margin: "18px 0 10px" }}>
              <span className="l">PRESENCE CHECK — TRY HER STATES</span>
              <span className="rule" />
            </div>
            <div className="pillrow">
              {(["idle", "listening", "thinking", "speaking", "alert"] as EveMode[]).map((st) => (
                <button
                  key={st}
                  className={`pill6${mode === st ? ` on${st === "alert" ? " alert" : ""}` : ""}`}
                  onClick={() => previewState(st)}
                >
                  {st.toUpperCase()}
                </button>
              ))}
            </div>

            <div className="acclock">
              <span className="k">ACCENT — TEAL</span>
              <span className="s">locked. she chose it herself.</span>
            </div>
          </div>
        )}

        {/* ---------- nav ---------- */}
        <nav className="nav6">
          {([
            ["today", "TODAY"],
            ["eve", "EVE"],
            ["ops", "OPS"],
            ["wire", "WIRE"],
          ] as const).map(([id, lab]) => (
            <button
              key={id}
              className={`navi${tab === id ? " on" : ""}`}
              onClick={() => setTab(id)}
              aria-label={lab}
              aria-current={tab === id ? "page" : undefined}
            >
              <span className="tick" />
              {id === "today" && (
                <svg viewBox="0 0 20 20" style={{ width: 19, height: 19, fill: "none", stroke: tab === id ? "#1CB9C8" : "rgba(240,237,232,.42)", strokeWidth: 1.5, strokeLinecap: "round" }}>
                  <circle cx="10" cy="8.5" r="4" /><path d="M2.5 16.5h15" />
                </svg>
              )}
              {id === "eve" && (
                <svg viewBox="0 0 20 20" style={{ width: 19, height: 19, fill: "none", stroke: tab === id ? "#1CB9C8" : "rgba(240,237,232,.42)", strokeWidth: 1.5 }}>
                  <circle cx="10" cy="10" r="4.2" /><ellipse cx="10" cy="10" rx="8.5" ry="3.2" transform="rotate(-16 10 10)" />
                </svg>
              )}
              {id === "ops" && (
                <svg viewBox="0 0 20 20" style={{ width: 19, height: 19, fill: "none", stroke: tab === id ? "#1CB9C8" : "rgba(240,237,232,.42)", strokeWidth: 1.5, strokeLinecap: "round" }}>
                  <path d="M3 5.5h14" /><path d="M3 10h9" /><circle cx="16" cy="10" r="1.6" /><path d="M3 14.5h12" />
                </svg>
              )}
              {id === "wire" && (
                <svg viewBox="0 0 20 20" style={{ width: 19, height: 19, fill: "none", stroke: tab === id ? "#1CB9C8" : "rgba(240,237,232,.42)", strokeWidth: 1.4, strokeLinecap: "round" }}>
                  <circle cx="4.5" cy="5" r="1.7" /><circle cx="15.5" cy="6.5" r="1.7" /><circle cx="6.5" cy="15" r="1.7" /><circle cx="14.5" cy="14" r="1.7" />
                  <path d="M6 5.7l7.8 0.6" /><path d="M5.2 6.6l1 6.7" /><path d="M8.2 14.6l4.6-0.4" /><path d="M15 8.2l-0.3 4.1" />
                </svg>
              )}
              <span className="lb mono">{lab}</span>
            </button>
          ))}
        </nav>

        <div className="scan" />
        <div className="vig" />

        {/* ---------- boot ---------- */}
        {!booted && (
          <div className={`boot${bootLeaving ? " boot-out" : ""}`}>
            <EveEntity mode="idle" />
            <div className="wm disp">EVE</div>
            <div className="ws mono">EXECUTIVE VOICE ENGINE · CHURLISH MEDIA</div>
            <button className="wakeb" onClick={wake}>
              WAKE HER UP
            </button>
          </div>
        )}
      </div>
    </div>
  );
}
