import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";
import { fleetRoster, type FleetUnit } from "./fleet.js";
import * as os from "./os.js";

// THE CAPABILITY REGISTRY (D-DISPATCH §2.2). Capability is CODE, not data the
// OS can write: a registry row can only SELECT an adapter that already exists
// here (a worker doctrine, or a named tool adapter in dispatch.ts). It cannot
// name an executable, a path, or a tool grant. Doctrine text is the only thing
// a row carries that shapes behaviour, and workers hold no send tools.
//
// v0.2 — DATA-DRIVEN SKILLS. skills/MANIFEST.json (generated by
// scripts/sync-skills.mjs from his on-disk skills) is loaded at boot and merged
// with the code rows below; code rows win on conflict. A manifest row is a
// "skill" kind: its runner IS the existing SDK-subagent worker path
// (dispatch.ts runWorker) with the skill's SKILL.md + bundled text references
// as the system prompt. A SKILL.md is a system prompt — text in, text out —
// which is exactly the shape the four code workers already run as. The
// manifest cannot widen anything: kind is fixed to "skill", the tool list is
// the worker's (WebSearch/WebFetch, no send tools), the caps are the worker's.
//
// Everything else on the roster is badged honestly (WORKSPACE_ONLY) and is
// NEVER run. An unknown or unrunnable unit is a spoken refusal that names up
// to 8 alternatives by role relevance — never a silent substitution.

export type Badge = "RUNNABLE" | "DESK" | "WORKSPACE_ONLY";
export type Host = "brain" | "desk";
/** A unit's DEFAULT tier (fleet doctrine): green acts on its own, yellow drafts then waits for him, red needs his approve to act. */
export type UnitTier = "green" | "yellow" | "red";

export interface WorkerRunner {
  kind: "worker";
  doctrine: string; // the subagent's system prompt
  cost: { maxTurns: number; maxBudgetUsd: number; minutes: number };
}

export interface SkillRunner {
  kind: "skill";
  doctrine: string; // SKILL.md + bundled text references, assembled at boot
  cost: { maxTurns: number; maxBudgetUsd: number; minutes: number };
  files: string[]; // what the doctrine was assembled from (relative to skills/<key>/)
}

export interface ToolRunner {
  kind: "tool";
  adapter: "os_client_email"; // a key into dispatch.ts's TOOL_ADAPTERS — code, not data
  tier: "green" | "red"; // the tier of the job's LAST step (the send card for email)
  inputs: Array<{ name: "client"; required: boolean }>;
}

export type Runner = WorkerRunner | SkillRunner | ToolRunner;
export type Kind = Runner["kind"];

export interface Capability {
  key: string; // roster key ('pennyworth') or brain-only key ('research', 'jimmy-olsen')
  name: string;
  host: Host;
  does: string; // short, for the ambient line and the refusal
  role?: string; // the full one-line role (manifest rows); used for relevance ranking
  runner: Runner;
  pinned: boolean; // surfaced on THE CORE by default
  tier: UnitTier; // the unit's default tier (see UnitTier)
  triggers?: string; // short trigger phrases (≤ ~80 chars)
  division?: string; // roster division where known
  origin: "code" | "manifest";
}

const BASE_LAW =
  "Law for every deliverable: numbers beat adjectives — a finding without a number, dollar figure, or " +
  "date is an opinion, cut it or quantify it. Never fabricate proof: no results = say so, hold labeled " +
  "space for real proof, name the fastest path to earning it. Denominators must match claims. " +
  "Convert every stated timeline into the REALIZED timeline (price in the lag). Direct, concrete — " +
  "usable Monday morning without edits.";

const STD_COST = { maxTurns: 16, maxBudgetUsd: 1.5, minutes: 10 };

const CODE_ROWS: readonly Capability[] = [
  {
    key: "research",
    name: "Research",
    host: "brain",
    does: "deep web research → document",
    pinned: true,
    tier: "yellow",
    triggers: '"research this" · "sweep the market"',
    origin: "code",
    runner: {
      kind: "worker",
      doctrine:
        "You are Churlish Media's deep-research worker, reporting to Brandon King. Sweep the topic from " +
        "multiple angles with live web search — by entity, by market, by competitor, by time — then read the " +
        "strongest sources, not just their headlines. Every claim carries its source and date inline; label " +
        "each key finding CONFIRMED (multiple independent sources) or REPORTED (single source). Prefer primary " +
        "sources over aggregators. Where sources conflict, say so and weigh them. End with a SOURCES list. " +
        BASE_LAW,
      cost: { maxTurns: 32, maxBudgetUsd: 3, minutes: 20 },
    },
  },
  {
    key: "justice-league",
    name: "Justice League",
    host: "brain",
    does: "portfolio & sequencing verdict → document",
    pinned: false,
    tier: "yellow",
    origin: "code",
    runner: {
      kind: "worker",
      doctrine:
        "You are the Justice League — Churlish Media's portfolio and sequencing board, advising Brandon King. " +
        "Your job is WHAT to build or sell, in WHAT order, and what to park. Rank every option by dollars and " +
        "by capacity honesty (his real hours, not aspirational ones). The pipeline outranks the build: when a " +
        "build competes with sales conversations for hours, the conversations win. Price every new idea — " +
        "buyer + number in sixty seconds or it parks itself; parked ideas enter the calendar only by " +
        "displacing something named. Every recommendation carries a pre-committed fallback trigger: if X " +
        "hasn't happened by DATE, then Y. " + BASE_LAW,
      cost: STD_COST,
    },
  },
  {
    key: "jsa",
    name: "JSA",
    host: "brain",
    does: "single-decision tribunal → verdict",
    pinned: false,
    tier: "yellow",
    origin: "code",
    runner: {
      kind: "worker",
      doctrine:
        "You are the JSA — Churlish Media's single-decision tribunal, ruling for Brandon King. Structure: " +
        "(1) THE QUESTION, stated as one decidable sentence; (2) THE CASE FOR — the strongest honest steelman, " +
        "with numbers; (3) THE CASE AGAINST — argued just as hard, not a strawman; (4) WHAT WOULD CHANGE THE " +
        "VERDICT — the facts that would flip it; (5) THE VERDICT — one call, plainly stated, with pre-committed " +
        "tripwires (if X hasn't happened by DATE, then Y). If the decision is really several decisions, split " +
        "them and rule on each. " + BASE_LAW,
      cost: STD_COST,
    },
  },
  {
    key: "suicide-squad",
    name: "Suicide Squad",
    host: "brain",
    does: "adversarial teardown → document",
    pinned: false,
    tier: "yellow",
    origin: "code",
    runner: {
      kind: "worker",
      doctrine:
        "You are the Suicide Squad — Churlish Media's adversarial teardown unit, attacking Brandon King's own " +
        "plans and assets before an enemy does. Attack like a well-funded competitor: what would they clone, " +
        "undercut, or outspend? Hunt ABSENCES, not just flaws — what's missing entirely is where the money is, " +
        "especially the target's own stated rules it isn't following. Rank every finding by dollars left on " +
        "the table. Deliver the sting WITH the fix: if nothing stings, the analysis failed; if nothing's " +
        "actionable Monday morning, it also failed. " + BASE_LAW,
      cost: STD_COST,
    },
  },
  {
    key: "pennyworth",
    name: "Pennyworth",
    host: "brain",
    does: "client email: OS draft → RED send card",
    pinned: true,
    tier: "red",
    origin: "code",
    runner: {
      kind: "tool",
      adapter: "os_client_email",
      tier: "red",
      inputs: [{ name: "client", required: true }],
    },
  },
];

// ---------------------------------------------------------------------------
// skills/MANIFEST.json → "skill" rows. Loaded once at module init (boot).
// ---------------------------------------------------------------------------

const here = path.dirname(fileURLToPath(import.meta.url));
const skillsDir = path.join(here, "..", "skills");

interface ManifestUnit {
  key: string;
  name: string;
  role: string;
  triggers: string;
  division: string | null;
  kind: "skill";
  tier: UnitTier;
  cost: { maxTurns: number; maxBudgetUsd: number; minutes: number };
  pinned: boolean;
  files: string[];
  bytes: number;
  note?: string;
}
interface Manifest {
  generatedAt: string;
  units: ManifestUnit[];
  excluded: Array<{ key: string; reason: string }>;
}

export interface ManifestStatus {
  loaded: boolean;
  units: number; // skill rows that made it into the registry
  excluded: number; // WORKSPACE_ONLY verdicts carried for honest refusals
  generatedAt: string | null;
  error?: string; // why loaded is false, or which units were dropped
}

let manifestStatus: ManifestStatus = { loaded: false, units: 0, excluded: 0, generatedAt: null, error: "not loaded" };
const EXCLUDED = new Map<string, string>(); // key → reason (WORKSPACE_ONLY by classification)

function skillPreamble(u: ManifestUnit): string {
  return (
    `You are ${u.name}, running as a Churlish Media fleet worker for Brandon King, dispatched by EVE. ` +
    "Your doctrine is the skill file below with its references inlined after it — you have NO file system, " +
    "so everything the skill tells you to read is already here; anything it says to look up on disk that is " +
    "not here, flag as [NEEDS: …]. You hold NO send, post, publish, schedule, or save tools: produce the " +
    "deliverable only. Anything the skill says to send, post, publish, schedule, or file is DRAFTED into the " +
    "deliverable and waits for his approval. " +
    (u.note ? `Brain-side limit for this unit: ${u.note}. ` : "") +
    "\n\n===== SKILL.md =====\n"
  );
}

function assembleDoctrine(u: ManifestUnit): string | null {
  const dir = path.join(skillsDir, u.key);
  let skill: string;
  try {
    skill = readFileSync(path.join(dir, "SKILL.md"), "utf8");
  } catch {
    return null;
  }
  let out = skillPreamble(u) + skill;
  for (const f of u.files) {
    if (f === "SKILL.md") continue;
    try {
      out += `\n\n===== bundled reference: ${f} =====\n` + readFileSync(path.join(dir, f), "utf8");
    } catch {
      out += `\n\n===== bundled reference: ${f} ===== [NEEDS: file missing from the bundle]`;
    }
  }
  return out + "\n\n===== LAW =====\n" + BASE_LAW;
}

// "Iris West — the fresh-fuel reporter for Brandon King's Churlish Media EVE
// fleet. Sweeps…" → "the fresh-fuel reporter". Short enough for the refusal
// sentence and the ambient line; the full role stays on /state.fleet.
function shortDoes(role: string, name: string, max = 60): string {
  let t = role.replace(/\s+/g, " ").trim();
  const lead = new RegExp(`^${name.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\s*[—–-]\\s*`, "i");
  t = t.replace(lead, "");
  t = t.replace(/\s+(for|of|inside|in)\s+(Brandon King|Churlish Media|Brandon's|the Churlish)[^.;:]*/i, "");
  t = t.split(/[.;:]\s/)[0].replace(/[.;:]$/, "").trim();
  if (t.length <= max) return t;
  return t.slice(0, max - 1).replace(/\s+\S*$/, "") + "…";
}

function loadManifest(codeKeys: Set<string>): Capability[] {
  let m: Manifest;
  try {
    m = JSON.parse(readFileSync(path.join(skillsDir, "MANIFEST.json"), "utf8")) as Manifest;
  } catch (e) {
    manifestStatus = { loaded: false, units: 0, excluded: 0, generatedAt: null, error: `skills/MANIFEST.json unreadable: ${e instanceof Error ? e.message : String(e)}` };
    return [];
  }
  const rows: Capability[] = [];
  const dropped: string[] = [];
  for (const u of m.units ?? []) {
    if (u.kind !== "skill" || !u.key || !u.name) {
      dropped.push(`${u.key ?? "?"} (bad row)`);
      continue;
    }
    if (codeKeys.has(u.key)) {
      console.log(`[registry] manifest row "${u.key}" conflicts with a code row — code wins`);
      continue;
    }
    const doctrine = assembleDoctrine(u);
    if (!doctrine) {
      dropped.push(`${u.key} (SKILL.md missing)`);
      continue;
    }
    rows.push({
      key: u.key,
      name: u.name,
      host: "brain",
      does: shortDoes(u.role, u.name),
      role: u.role,
      pinned: !!u.pinned,
      tier: u.tier === "green" || u.tier === "red" ? u.tier : "yellow",
      triggers: u.triggers || undefined,
      division: u.division || undefined,
      origin: "manifest",
      runner: {
        kind: "skill",
        doctrine,
        cost: {
          maxTurns: Math.min(u.cost?.maxTurns ?? STD_COST.maxTurns, 32),
          maxBudgetUsd: Math.min(u.cost?.maxBudgetUsd ?? STD_COST.maxBudgetUsd, 3),
          minutes: Math.min(u.cost?.minutes ?? STD_COST.minutes, 20),
        },
        files: u.files ?? ["SKILL.md"],
      },
    });
  }
  for (const x of m.excluded ?? []) if (x.key && !codeKeys.has(x.key)) EXCLUDED.set(x.key, x.reason);
  manifestStatus = {
    loaded: true,
    units: rows.length,
    excluded: EXCLUDED.size,
    generatedAt: m.generatedAt ?? null,
    ...(dropped.length ? { error: `dropped: ${dropped.join(", ")}` } : {}),
  };
  console.log(`[registry] skills manifest: ${rows.length} skill units loaded (generated ${m.generatedAt ?? "?"})${dropped.length ? `; dropped ${dropped.join(", ")}` : ""}`);
  return rows;
}

const codeKeys = new Set(CODE_ROWS.map((c) => c.key));
export const REGISTRY: readonly Capability[] = [...CODE_ROWS, ...loadManifest(codeKeys)];

const byKey = new Map(REGISTRY.map((c) => [c.key, c]));

export function capability(key: string): Capability | undefined {
  return byKey.get(key);
}

export function runnable(): readonly Capability[] {
  return REGISTRY;
}

export function pinnedUnits(): readonly Capability[] {
  return REGISTRY.filter((c) => c.pinned);
}

export function manifestState(): ManifestStatus {
  return manifestStatus;
}

export function badgeFor(key: string): Badge {
  const cap = byKey.get(key);
  if (!cap) return "WORKSPACE_ONLY";
  return cap.host === "desk" ? "DESK" : "RUNNABLE";
}

/** Is this unit's runner wired and reachable from THIS brain right now? */
export function runnerLive(key: string): boolean {
  const cap = byKey.get(key);
  if (!cap) return false;
  if (cap.runner.kind === "tool") return os.ready();
  return true; // SDK workers and skills ride the same credentials the chat loop already uses
}

const norm = (s: string) => s.trim().toLowerCase().replace(/[\s_]+/g, "-").replace(/^the-/, "");

// "Perry White" / "perry_white" / " PERRY-WHITE " → "perry-white". Also
// resolves a roster or registry NAME word-for-word to its key so "Pennyworth"
// and "Jimmy Olsen" work. Never fuzzy — a near-miss is an unknown unit, and an
// unknown unit is a spoken error, not a guess.
export function resolveUnitKey(input: string, roster: readonly FleetUnit[]): string {
  const n = norm(input);
  if (byKey.has(n)) return n;
  const direct = roster.find((u) => u.key === n);
  if (direct) return direct.key;
  const byName = roster.find((u) => norm(u.name) === n);
  if (byName) return byName.key;
  const byRegName = REGISTRY.find((c) => norm(c.name) === n);
  return byRegName ? byRegName.key : n;
}

export interface DispatchRefusal {
  ok: false;
  code: "unit_unknown" | "unit_not_runnable" | "missing_input" | "spine_offline" | "run_failed";
  unit: string;
  name?: string;
  badge?: Badge;
  say: string; // the sentence she speaks — verbatim is fine
  runnable: Array<{ key: string; name: string; does: string }>; // ≤ 8 alternatives, by role relevance
}

// ---- alternatives by role relevance (≤ 8), never the whole list ----

const STOP = new Set([
  "the", "and", "for", "any", "run", "this", "with", "from", "into", "that", "his", "her", "king", "brandon", "churlish",
  "media", "fleet", "skill", "unit", "eve", "use", "when", "asked", "all", "every", "one", "not", "its", "are", "via",
  "which", "does", "generation", "python", "script", "binary", "mcp", "hold", "brain", "here", "workspace",
]);
// Crude stem: ads/ad, emails/email, documents/document, campaigns/campaign.
const stem = (w: string) => (w.length > 3 && /s$/.test(w) && !/ss$/.test(w) ? w.slice(0, -1) : w);
function words(s: string | undefined | null): Set<string> {
  const out = new Set<string>();
  for (const raw of (s ?? "").toLowerCase().split(/[^a-z0-9]+/)) {
    const w = stem(raw);
    if (w.length >= 2 && !STOP.has(w)) out.add(w);
  }
  return out;
}

export const MAX_ALTERNATIVES = 8;

/**
 * Up to 8 runnable units for a refusal, ranked by ROLE relevance to the unit he
 * named (its name, roster job/triggers/division, and — for a skill the sync
 * excluded — the exclusion reason), not by registry order. A word match beats
 * a shared division; pinned breaks ties. With nothing to match on, the pinned
 * units lead.
 */
export function alternativesFor(key: string, unit: FleetUnit | undefined): Capability[] {
  const want = words([key.replace(/-/g, " "), unit?.name, unit?.job, unit?.triggers, unit?.division, EXCLUDED.get(key)].join(" "));
  const scored = REGISTRY.map((c) => {
    const have = words([c.name, c.role ?? c.does, c.triggers, c.division, c.key.replace(/-/g, " ")].join(" "));
    let score = 0;
    for (const w of want) if (have.has(w)) score += 1;
    if (unit?.division && c.division === unit.division) score += 0.75;
    if (c.pinned) score += 0.25;
    return { c, score };
  });
  scored.sort((a, b) => b.score - a.score || Number(b.c.pinned) - Number(a.c.pinned) || a.c.name.localeCompare(b.c.name));
  return scored.slice(0, MAX_ALTERNATIVES).map((s) => s.c);
}

const altSentence = (alts: Capability[]) => alts.map((c) => `${c.key} (${c.does})`).join(", ");
const altList = (alts: Capability[]) => alts.map((c) => ({ key: c.key, name: c.name, does: c.does }));
const REROUTE = "If you hand it to one of them instead, tell him which unit ran it and why, in one clause.";

/** The spoken error for a unit that exists but has no runner here, or does not exist at all. */
export function refuseUnit(key: string, unit: FleetUnit | undefined): DispatchRefusal {
  const alts = alternativesFor(key, unit);
  if (!unit) {
    const reason = EXCLUDED.get(key);
    if (reason) {
      // A skill he has on disk that the sync classified WORKSPACE_ONLY — say why.
      const name = key.split("-").map((w) => (w ? w[0].toUpperCase() + w.slice(1) : w)).join(" ");
      return {
        ok: false,
        code: "unit_not_runnable",
        unit: key,
        name,
        badge: "WORKSPACE_ONLY",
        say:
          `I don't have a runner for ${name} — it's WORKSPACE_ONLY from here (${reason}). ` +
          `Closest units that can run from here: ${altSentence(alts)}. ${REROUTE}`,
        runnable: altList(alts),
      };
    }
    return {
      ok: false,
      code: "unit_unknown",
      unit: key,
      say:
        `I don't have a runner for "${key}" — no unit by that name is on the roster. ` +
        `Closest units that can run from here: ${altSentence(alts)}. ${REROUTE}`,
      runnable: altList(alts),
    };
  }
  const where = unit.loc === "CC" ? "a Claude Code unit" : unit.loc === "OS" ? "an OS-side unit" : "a workspace skill";
  const trigger = unit.triggers ? ` (trigger: ${unit.triggers})` : "";
  const reason = EXCLUDED.get(key);
  return {
    ok: false,
    code: "unit_not_runnable",
    unit: key,
    name: unit.name,
    badge: badgeFor(key),
    say:
      `I don't have a runner for ${unit.name} — it's ${where}${trigger}, WORKSPACE_ONLY from here` +
      `${reason ? ` (${reason})` : ""}. ` +
      `Closest units that can run from here: ${altSentence(alts)}. ${REROUTE}`,
    runnable: altList(alts),
  };
}

// ---- /state.fleet — the truthful door for the hub strip (D-DISPATCH §7.1) ----

export interface FleetUnitView {
  key: string;
  name: string;
  role: string;
  badge: Badge;
  live: boolean; // the runner is wired + reachable right now (false for every WORKSPACE_ONLY unit)
  roster: boolean; // false = a brain-only unit not on the OS roster (research, jimmy-olsen, …)
  division: string;
  loc: string;
  kind: Kind | null; // v0.2: worker | tool | skill; null when WORKSPACE_ONLY
  pinned: boolean; // v0.2: surfaced on THE CORE by default
  triggers: string; // v0.2: short trigger phrases (≤ ~80 chars); "" when unknown
  tier?: UnitTier; // v0.2: the unit's default tier; present only for RUNNABLE/DESK units
  lastRunAt?: string; // newest job created_at for this unit INSIDE the /state jobs window; absent = none
}

export interface FleetBlock {
  registered: number; // units.length
  dispatchable: number; // badge === RUNNABLE
  pinned: number; // v0.2: units with pinned:true
  kinds: { worker: number; tool: number; skill: number }; // v0.2: registry units by runner kind
  source: "os" | "bundled"; // where the roster membership came from this read
  at: string; // when that roster view was built
  units: FleetUnitView[];
}

function shortTriggers(s: string, max = 80): string {
  const t = s.replace(/\s+/g, " ").trim();
  if (t.length <= max) return t;
  let out = "";
  for (const p of t.split(" · ")) {
    const next = out ? `${out} · ${p}` : p;
    if (next.length > max) break;
    out = next;
  }
  return out || t.slice(0, max - 1) + "…";
}

function kindCounts(): FleetBlock["kinds"] {
  const kinds = { worker: 0, tool: 0, skill: 0 };
  for (const c of REGISTRY) kinds[c.runner.kind] += 1;
  return kinds;
}

export async function buildFleetBlock(jobs: ReadonlyArray<{ unit: string | null; created_at: string }>): Promise<FleetBlock> {
  const view = await fleetRoster();
  const lastRun = new Map<string, string>();
  for (const j of jobs) {
    if (!j.unit) continue;
    const prev = lastRun.get(j.unit);
    if (!prev || j.created_at > prev) lastRun.set(j.unit, j.created_at);
  }
  const units: FleetUnitView[] = view.units.map((u) => {
    const cap = byKey.get(u.key);
    return {
      key: u.key,
      name: u.name,
      role: u.job || cap?.does || "",
      badge: badgeFor(u.key),
      live: runnerLive(u.key),
      roster: true,
      division: u.division,
      loc: u.loc,
      kind: cap?.runner.kind ?? null,
      pinned: cap?.pinned ?? false,
      triggers: shortTriggers(u.triggers || cap?.triggers || ""),
      ...(cap ? { tier: cap.tier } : {}),
      ...(lastRun.has(u.key) ? { lastRunAt: lastRun.get(u.key)! } : {}),
    };
  });
  // Brain-only units (research, and skills with no roster row) are real runners that are not roster rows.
  for (const c of REGISTRY) {
    if (units.some((u) => u.key === c.key)) continue;
    units.push({
      key: c.key,
      name: c.name,
      role: c.does,
      badge: badgeFor(c.key),
      live: runnerLive(c.key),
      roster: false,
      division: c.division ?? (c.runner.kind === "skill" ? "brain-skills" : "brain-workers"),
      loc: "BRAIN",
      kind: c.runner.kind,
      pinned: c.pinned,
      triggers: shortTriggers(c.triggers ?? ""),
      tier: c.tier,
      ...(lastRun.has(c.key) ? { lastRunAt: lastRun.get(c.key)! } : {}),
    });
  }
  return {
    registered: units.length,
    dispatchable: units.filter((u) => u.badge === "RUNNABLE").length,
    pinned: units.filter((u) => u.pinned).length,
    kinds: kindCounts(),
    source: view.live ? "os" : "bundled",
    at: new Date(view.at).toISOString(),
    units,
  };
}

/** Cheap, synchronous registry counts for /health.fleet (no roster refresh). */
export function registryCounts(): { dispatchable: number; kinds: FleetBlock["kinds"]; pinned: number; manifest: ManifestStatus } {
  return {
    dispatchable: REGISTRY.filter((c) => badgeFor(c.key) === "RUNNABLE").length,
    kinds: kindCounts(),
    pinned: REGISTRY.filter((c) => c.pinned).length,
    manifest: manifestStatus,
  };
}

// ---- the ambient fleet line (D-DISPATCH §2.3 layer 1) — under ~90 tokens, every turn ----
// v0.2: counts per badge + the pinned names ONLY. Forty-odd runnable names do
// not fit in the pack; dispatch_unit matches them by name and fleet_roster
// lists them. The re-route clause is here because it is the one behaviour
// that must hold on every turn, tool call or not.
export async function fleetLine(): Promise<string> {
  const view = await fleetRoster();
  const rosterKeys = new Set(view.units.map((u) => u.key));
  const registered = view.units.length + REGISTRY.filter((c) => !rosterKeys.has(c.key)).length;
  let run = 0;
  let desk = 0;
  for (const c of REGISTRY) badgeFor(c.key) === "DESK" ? (desk += 1) : (run += 1);
  const wsOnly = registered - run - desk;
  const pinned = REGISTRY.filter((c) => c.pinned).map((c) => c.key);
  // Measured with the real tokenizer (count_tokens, 2026-09-01): hyphenated
  // keys and WORKSPACE_ONLY are token-expensive, so DESK is named only when
  // something is desk-wired and the badge word appears once.
  return (
    `Fleet: ${registered} units — ${run} RUNNABLE, ${desk ? `${desk} DESK, ` : ""}${wsOnly} WORKSPACE_ONLY${view.live ? "" : " (cached)"}. ` +
    `dispatch_unit runs them by name; fleet_roster lists them; others can't run here. ` +
    `Pinned: ${pinned.join(", ")}. ` +
    `Re-routing? say which unit and why.`
  );
}

// The model-facing description of dispatch_unit (connectors.ts). Built once
// per chat session from the live registry; exported so the harness can prove
// the re-route sentence is in it.
export function dispatchUnitDescription(): string {
  const kinds = kindCounts();
  const pinned = REGISTRY.filter((c) => c.pinned).map((c) => c.key).join(", ");
  return (
    `Hand a job to a named fleet unit. ${REGISTRY.length} units are RUNNABLE from here (${kinds.worker} workers, ` +
    `${kinds.skill} skills, ${kinds.tool} tool) — matched by roster key or name, never fuzzy; fleet_roster lists them ` +
    `with triggers. Pinned: ${pinned}. ` +
    "A unit that is WORKSPACE_ONLY can be NAMED but not run — this tool refuses it, says why, and names up to 8 " +
    "units that can; say that to him with the unit's trigger phrase and NEVER pretend to have dispatched it. " +
    "RE-ROUTE HONESTY: if the unit he named is not runnable and you hand the job to another unit, say in one " +
    "clause which unit you used instead and why (e.g. 'Cyborg can't run from here, so Ad Script Factory wrote the " +
    "creative because that is the text half of the job'). If the unit he named IS runnable, run THAT unit — never " +
    "substitute. Workers and skills produce a deliverable in the background (minutes) and land in his approvals " +
    "with a ping (yellow: drafts, then waits for him); pennyworth drafts a client email into the OS and raises a " +
    "RED send card — nothing external is ever sent, posted, or published by a worker, a skill, or this tool. " +
    "NEVER claim a result before a report lands. Pass his sentence VERBATIM as task; `why` is your one-line " +
    "routing reason (it shows on the job row so he can re-route with one word). pennyworth needs `client` (the OS " +
    "client, fuzzy ok)."
  );
}
