import { randomBytes } from "node:crypto";
import { resolve } from "node:path";
import { defineConfig, externalizeDepsPlugin } from "electron-vite";
import react from "@vitejs/plugin-react";

// electron-vite with an explicit layout: the main/preload sources live in
// electron/, the renderer's three HTML entries live at the package root, and
// the shared contract is imported by BOTH sides from src/shared.
//
// JSX note: @vitejs/plugin-react was added in the S1b bridge wave so S2-S4 get
// React Fast Refresh (component state survives an edit) instead of a full
// reload on every save. Before this it rode on esbuild's `"jsx": "react-jsx"`
// transform alone, which compiles .tsx fine but has no Fast Refresh.
//
// Owning stream: S1 / S1b. FROZEN for wave 2 (S2/S3/S4 do not edit this file).

// ---------------------------------------------------------------------------
// THE BUILD STAMP (S4, 2026-09-01). Edited under the voice/diagnosability
// mandate; the rest of this file is still S1's and still frozen.
//
// One string, computed ONCE per `electron-vite build` invocation, inlined as a
// literal into out/main, out/preload and out/renderer alike. This module body
// runs once when electron-vite loads the config, and all three target configs
// below close over the same constant — that is the whole mechanism, and it is
// why the three halves cannot disagree unless they came from different builds.
//
// It is deliberately NOT read from disk at runtime. Two halves that both stat
// the same out/ directory agree even when one of them is a year old — see
// src/shared/build-stamp.ts for the incident that proves it.
//
// The random tail exists so two builds within the same second are still two
// different stamps.
// ---------------------------------------------------------------------------
const BUILD_STAMP = `${new Date().toISOString()}#${randomBytes(3).toString("hex")}`;

const stampDefine = { __EVE_BUILD_STAMP__: JSON.stringify(BUILD_STAMP) };

export default defineConfig({
  main: {
    define: stampDefine,
    plugins: [externalizeDepsPlugin()],
    build: {
      outDir: "out/main",
      rollupOptions: { input: { index: resolve(__dirname, "electron/main.ts") } },
    },
  },
  preload: {
    define: stampDefine,
    plugins: [externalizeDepsPlugin()],
    build: {
      outDir: "out/preload",
      rollupOptions: { input: { index: resolve(__dirname, "electron/preload.ts") } },
    },
  },
  renderer: {
    define: stampDefine,
    root: __dirname,
    plugins: [react()],
    resolve: {
      alias: { "@shared": resolve(__dirname, "src/shared") },
    },
    build: {
      outDir: "out/renderer",
      rollupOptions: {
        input: {
          deck: resolve(__dirname, "index.html"),
          summon: resolve(__dirname, "summon.html"),
          flyout: resolve(__dirname, "flyout.html"),
        },
      },
    },
  },
});
